/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dao;

import senior.hrms.emps.dto.*;
import senior.hrms.emps.exceptions.*;

public interface MissionTypesDao
{
	/** 
	 * Inserts a new row in the MISSION_TYPES table.
	 */
	public MissionTypesPk insert(MissionTypes dto) throws MissionTypesDaoException;

	/** 
	 * Updates a single row in the MISSION_TYPES table.
	 */
	public void update(MissionTypesPk pk, MissionTypes dto) throws MissionTypesDaoException;

	/** 
	 * Deletes a single row in the MISSION_TYPES table.
	 */
	public void delete(MissionTypesPk pk) throws MissionTypesDaoException;

	/** 
	 * Returns the rows from the MISSION_TYPES table that matches the specified primary-key value.
	 */
	public MissionTypes findByPrimaryKey(MissionTypesPk pk) throws MissionTypesDaoException;

	/** 
	 * Returns all rows from the MISSION_TYPES table that match the criteria 'MISSION_TYPE_ID = :missionTypeId'.
	 */
	public MissionTypes findByPrimaryKey(int missionTypeId) throws MissionTypesDaoException;

	/** 
	 * Returns all rows from the MISSION_TYPES table that match the criteria ''.
	 */
	public MissionTypes[] findAll() throws MissionTypesDaoException;

	/** 
	 * Returns all rows from the MISSION_TYPES table that match the criteria 'MISSION_TYPE_ID = :missionTypeId'.
	 */
	public MissionTypes[] findWhereMissionTypeIdEquals(int missionTypeId) throws MissionTypesDaoException;

	/** 
	 * Returns all rows from the MISSION_TYPES table that match the criteria 'MISSION_TYPE_NAME = :missionTypeName'.
	 */
	public MissionTypes[] findWhereMissionTypeNameEquals(String missionTypeName) throws MissionTypesDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the MISSION_TYPES table that match the specified arbitrary SQL statement
	 */
	public MissionTypes[] findByDynamicSelect(String sql, Object[] sqlParams) throws MissionTypesDaoException;

	/** 
	 * Returns all rows from the MISSION_TYPES table that match the specified arbitrary SQL statement
	 */
	public MissionTypes[] findByDynamicWhere(String sql, Object[] sqlParams) throws MissionTypesDaoException;

}
