/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dao;

import senior.hrms.emps.dto.*;
import senior.hrms.emps.exceptions.*;

public interface OfficialVacationsSchedTrgDao
{
	/**
	 * Method 'execute'
	 * 
	 * @param param
	 * @throws OfficialVacationsSchedTrgDaoException
	 */
	public void execute(OfficialVacationsSchedTrgParam param) throws OfficialVacationsSchedTrgDaoException;

}
