/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dao;

import senior.hrms.emps.dto.*;
import senior.hrms.emps.exceptions.*;

public interface ResponsibilitiesDao
{
	/** 
	 * Inserts a new row in the RESPONSIBILITIES table.
	 */
	public ResponsibilitiesPk insert(Responsibilities dto) throws ResponsibilitiesDaoException;

	/** 
	 * Updates a single row in the RESPONSIBILITIES table.
	 */
	public void update(ResponsibilitiesPk pk, Responsibilities dto) throws ResponsibilitiesDaoException;

	/** 
	 * Deletes a single row in the RESPONSIBILITIES table.
	 */
	public void delete(ResponsibilitiesPk pk) throws ResponsibilitiesDaoException;

	/** 
	 * Returns the rows from the RESPONSIBILITIES table that matches the specified primary-key value.
	 */
	public Responsibilities findByPrimaryKey(ResponsibilitiesPk pk) throws ResponsibilitiesDaoException;

	/** 
	 * Returns all rows from the RESPONSIBILITIES table that match the criteria 'RESPONSIBILITY_ID = :responsibilityId'.
	 */
	public Responsibilities findByPrimaryKey(int responsibilityId) throws ResponsibilitiesDaoException;

	/** 
	 * Returns all rows from the RESPONSIBILITIES table that match the criteria ''.
	 */
	public Responsibilities[] findAll() throws ResponsibilitiesDaoException;

	/** 
	 * Returns all rows from the RESPONSIBILITIES table that match the criteria 'RESPONSIBILITY_ID = :responsibilityId'.
	 */
	public Responsibilities[] findWhereResponsibilityIdEquals(int responsibilityId) throws ResponsibilitiesDaoException;

	/** 
	 * Returns all rows from the RESPONSIBILITIES table that match the criteria 'RESPONSIBILITY_NAME = :responsibilityName'.
	 */
	public Responsibilities[] findWhereResponsibilityNameEquals(String responsibilityName) throws ResponsibilitiesDaoException;

	/** 
	 * Returns all rows from the RESPONSIBILITIES table that match the criteria 'DESCRIPTION = :description'.
	 */
	public Responsibilities[] findWhereDescriptionEquals(String description) throws ResponsibilitiesDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the RESPONSIBILITIES table that match the specified arbitrary SQL statement
	 */
	public Responsibilities[] findByDynamicSelect(String sql, Object[] sqlParams) throws ResponsibilitiesDaoException;

	/** 
	 * Returns all rows from the RESPONSIBILITIES table that match the specified arbitrary SQL statement
	 */
	public Responsibilities[] findByDynamicWhere(String sql, Object[] sqlParams) throws ResponsibilitiesDaoException;

}
