/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login.forms;

import admin.handler.*;
import com.Common;
import com.Test;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.*;
import login.handler.*;
import senior.hrms.emps.dto.*;
import senior.hrms.emps.exceptions.*;

/**
 *
 * @author Hany Nigma
 */
public class HRLogin extends javax.swing.JFrame {

    public Common comObj;

    /**
     * Creates new form HRLogin
     *
     * @throws java.io.IOException
     */
    public HRLogin() throws IOException {
        comObj = new Common();

        initComponents();

        comObj.setFrameTitle(this);
        comObj.setFrameCopyRight(copyRightsLabel);
        comObj.loadLogo(logoView);
        msg.setVisible(false);

    }
// Check if CAPS_LOCK is on then Make a note to user

    private void checkCapslock() {
        int keyCode = KeyEvent.VK_CAPS_LOCK;

        if (keyCode == KeyEvent.VK_CAPS_LOCK && Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK)) {

            capsLockMsg.setText(" إنتبه : Caps Lock في حالة تنشيط");
            capsLockMsg.setVisible(true);
        } else {
            capsLockMsg.setText("");
            capsLockMsg.setVisible(false);
        }
    }
// Set Feilds blank

    private void setMsgVisableFalse() {
        msg.setText("");
        msg.setText("");
        msg.setVisible(false);
    }
// Check Users Roles Then Access to his Form

    private void accessByRole(String roleName) throws IOException {
        switch (roleName) {
            case "affiar": {
                comObj.showForm(new AffairParts(), this);

                break;
            }
            case "approval": {

                comObj.showForm(new ApprovalParts(), this);
                break;
            }
            case "admin": {
                comObj.showForm(new MainParts(), this);

            }
            break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userNameLabel = new javax.swing.JLabel();
        passWordLabel = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        enterButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        msg = new javax.swing.JLabel();
        viewPassword = new javax.swing.JCheckBox();
        capsLockMsg = new javax.swing.JLabel();
        copyRightsLabel = new javax.swing.JLabel();
        logoView = new org.jdesktop.swingx.JXImageView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(239, 239, 239));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "تـسجــيل الـــدخول", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Traditional Arabic", 1, 18), new java.awt.Color(0, 0, 102))); // NOI18N

        userNameLabel.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(0, 0, 102));
        userNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userNameLabel.setText("اسم المستخدم");
        userNameLabel.setToolTipText("");

        passWordLabel.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        passWordLabel.setForeground(new java.awt.Color(0, 0, 102));
        passWordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passWordLabel.setText("كلمة المــرور");
        passWordLabel.setToolTipText("");

        userName.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        userName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userName.setToolTipText("ادخل اسم المستخدم");
        userName.setName(""); // NOI18N
        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });
        userName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userNameKeyPressed(evt);
            }
        });

        password.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setToolTipText("ادخل كلمة السر");
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });

        enterButton.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        enterButton.setText("دخـول");
        enterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        cancelButton.setText("إلغـــاء");
        cancelButton.setToolTipText("لاعادة كتابة اسم المستخدم و كلمة السر");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        msg.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        msg.setForeground(new java.awt.Color(102, 0, 0));
        msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/resource"); // NOI18N
        msg.setText(bundle.getString("loginMessage")); // NOI18N

        viewPassword.setForeground(new java.awt.Color(153, 0, 0));
        viewPassword.setText("اظهر كلمة السر");
        viewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPasswordActionPerformed(evt);
            }
        });

        capsLockMsg.setBackground(new java.awt.Color(0, 0, 204));
        capsLockMsg.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(capsLockMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(password, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passWordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(passWordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameLabel)
                            .addComponent(capsLockMsg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewPassword))))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterButton)
                    .addComponent(cancelButton))
                .addGap(47, 47, 47)
                .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        copyRightsLabel.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        copyRightsLabel.setForeground(new java.awt.Color(0, 0, 102));
        copyRightsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyRightsLabel.setToolTipText("");

        logoView.setBackground(new java.awt.Color(234, 233, 231));

        javax.swing.GroupLayout logoViewLayout = new javax.swing.GroupLayout(logoView);
        logoView.setLayout(logoViewLayout);
        logoViewLayout.setHorizontalGroup(
            logoViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        logoViewLayout.setVerticalGroup(
            logoViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(copyRightsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(copyRightsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_enterButtonActionPerformed
    {//GEN-HEADEREND:event_enterButtonActionPerformed
        
            /////////////////// Test //////////////////////
        /*try
        {
            Test test = new Test();
            test.print();
            test.getAll();
        } catch (UsersDaoException ex)
        {
            System.out.println(">>" + ex.getMessage());
        }*/
            /////////////////////End: Test ///////////////////////////
                String roleName = "";
            // Check if user enterd username and password or not
            if (userName.getText().length() > 0 && userName.getText().length() <= 100 && password.getPassword().length > 0 && password.getPassword().length <= 100) {
            String name = userName.getText().trim();
            String psswrd = new String(password.getPassword());
            // connect to data base and get role name and name id
            try {
            LoginHandler handler = new LoginHandler();
            UserRoleHanler usrRolHandler = new UserRoleHanler();
            RoleHandler roleNamebyID = new RoleHandler();
            
            Users[] usrList = handler.isValidUsers(name, psswrd);
            if (usrList != null && usrList.length > 0) {
            Users user = usrList[0];
            
            Common.userName = user.getUserName();
            int usrId = user.getUserId();
            
            UsersRoles[] urList = usrRolHandler.getUserRolesByUserId(usrId);
            UsersRoles roleID = urList[0];
            int roleId = roleID.getRoleId();
            
            try {
            Roles rolName = roleNamebyID.getRoleByRoleId(roleId);
            roleName = rolName.getRoleName();
            Common.userPrivilege = roleName;
            } catch (RolesDaoException ex) {
            Logger.getLogger(HRLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            // get user privilege and User name//
            Common.userPrivilege = roleName;
            Common.userName = name;
            
            // forward to : User Role Form //
            accessByRole(roleName);
            
                System.out.println("");
            
            // Error Message if User name or password are wrong
            } else {
            msg.setVisible(true);
            msg.setText("أعد إدخال اسم مستخدم و كلمة مرور صحيحة");
            
            userName.setText("");
            password.setText("");
            }
            
            } catch (UsersDaoException | UsersRolesDaoException | IOException ex) {
            Logger.getLogger(HRLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
            } else {
            // if username and or pass word are blank show error msg and blank username and password
            msg.setVisible(true);
            msg.setText("من فضلك إدخل اسم مستخدم و كلمة مرور صحيحة");

            userName.setText("");
            password.setText("");
            }
            
           
    }//GEN-LAST:event_enterButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
    {//GEN-HEADEREND:event_cancelButtonActionPerformed
        // reset username and password to blank txt 
        password.setText("");
        userName.setText("");
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void viewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPasswordActionPerformed
        // set password visiable if selected 
        // defalute is not selected
        if (viewPassword.isSelected()) {
            password.setEchoChar((char) 0);
        } else {
            password.setEchoChar('*');
        }

    }//GEN-LAST:event_viewPasswordActionPerformed

    private void userNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameKeyPressed

        setMsgVisableFalse();

        checkCapslock();

    }//GEN-LAST:event_userNameKeyPressed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed

        setMsgVisableFalse();

        checkCapslock();

    }//GEN-LAST:event_passwordKeyPressed

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        // Submit if Enter are pressed
        password.requestFocus();
    }//GEN-LAST:event_userNameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // Submit if Enter are pressed
        enterButtonActionPerformed(evt);
    }//GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new HRLogin().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(HRLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel capsLockMsg;
    private javax.swing.JLabel copyRightsLabel;
    private javax.swing.JButton enterButton;
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.swingx.JXImageView logoView;
    private javax.swing.JLabel msg;
    private javax.swing.JLabel passWordLabel;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField userName;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JCheckBox viewPassword;
    // End of variables declaration//GEN-END:variables
}
