/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login.forms;

import com.Common;
import employees.forms.*;
import java.awt.Cursor;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import senior.hrms.emps.exceptions.AccidentTypesDaoException;
import senior.hrms.emps.exceptions.DiseaseTypesDaoException;
import senior.hrms.emps.exceptions.DiseasesDaoException;
import senior.hrms.emps.exceptions.HospitalsDaoException;
import senior.hrms.emps.exceptions.OrganDaoException;
import settings.forms.HRMS_General;

/**
 *
 * @author amal
 */
public class MainParts extends javax.swing.JFrame {

    Common comObj;

    /**
     * Creates new form MainParts
     *
     * @throws java.io.IOException
     */
    public MainParts() throws IOException {
        comObj = new Common();

        initComponents();

        comObj.setFrameTitle(this);
        comObj.setFrameCopyRight(jLabel1);
        // Full Screen //
        comObj.setFrameFullScreen(this);
        // load: logo //
        comObj.loadLogo(logoView);
        // load: iamges //
        loadImages();
    }

    /**
     *
     * @throws IOException
     */
    private void loadImages() throws IOException {
        int imgWidth = Integer.parseInt(comObj.resourceFile.getString("imageWidth"));
        int imgHeight = Integer.parseInt(comObj.resourceFile.getString("imageHeight"));

        String settingsImg = comObj.resourceFile.getString("imagesPath")
                + comObj.resourceFile.getString("settingsImg");

        String affairsImg = comObj.resourceFile.getString("imagesPath")
                + comObj.resourceFile.getString("affairsImg");

        String attendanceImg = comObj.resourceFile.getString("imagesPath")
                + comObj.resourceFile.getString("attendanceImg");

        String salaryImg = comObj.resourceFile.getString("imagesPath")
                + comObj.resourceFile.getString("salaryImg");

        String reportsImg = comObj.resourceFile.getString("imagesPath")
                + comObj.resourceFile.getString("reportsImg");

        String hierarchyImg = comObj.resourceFile.getString("imagesPath")
                + comObj.resourceFile.getString("hierarchyImg");

        String adminImg = comObj.resourceFile.getString("imagesPath")
                + comObj.resourceFile.getString("adminImg");

        String logoutImg = comObj.resourceFile.getString("imagesPath")
                + comObj.resourceFile.getString("logoutIcon");

        // adjust ImageView size //
        settingsView.setSize(imgWidth, imgHeight);
        affairsView.setSize(imgWidth, imgHeight);
        attendanceView.setSize(imgWidth, imgHeight);
        salaryView.setSize(imgWidth, imgHeight);
        reportsView.setSize(imgWidth, imgHeight);
        hierarchyView.setSize(imgWidth, imgHeight);
        adminView.setSize(imgWidth, imgHeight);
        logoutView.setSize(imgWidth, imgHeight);

        // load images inside ImageView //
        settingsView.setImage(new File(settingsImg));
        affairsView.setImage(new File(affairsImg));
        attendanceView.setImage(new File(attendanceImg));
        salaryView.setImage(new File(salaryImg));
        reportsView.setImage(new File(reportsImg));
        hierarchyView.setImage(new File(hierarchyImg));
        adminView.setImage(new File(adminImg));
        logoutView.setImage(new File(logoutImg));

        // disable the ImageView //
        settingsView.setEditable(false);
        affairsView.setEditable(false);
        attendanceView.setEditable(false);
        salaryView.setEditable(false);
        reportsView.setEditable(false);
        hierarchyView.setEditable(false);
        adminView.setEditable(false);
        logoutView.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingsView = new org.jdesktop.swingx.JXImageView();
        affairsView = new org.jdesktop.swingx.JXImageView();
        attendanceView = new org.jdesktop.swingx.JXImageView();
        salaryView = new org.jdesktop.swingx.JXImageView();
        reportsView = new org.jdesktop.swingx.JXImageView();
        hierarchyView = new org.jdesktop.swingx.JXImageView();
        adminView = new org.jdesktop.swingx.JXImageView();
        logoutView = new org.jdesktop.swingx.JXImageView();
        logoView = new org.jdesktop.swingx.JXImageView();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        settingsView.setMaximumSize(new java.awt.Dimension(204, 255));
        settingsView.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                settingsViewMouseMoved(evt);
            }
        });
        settingsView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsViewMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout settingsViewLayout = new javax.swing.GroupLayout(settingsView);
        settingsView.setLayout(settingsViewLayout);
        settingsViewLayout.setHorizontalGroup(
            settingsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );
        settingsViewLayout.setVerticalGroup(
            settingsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        affairsView.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                affairsViewMouseMoved(evt);
            }
        });
        affairsView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                affairsViewMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout affairsViewLayout = new javax.swing.GroupLayout(affairsView);
        affairsView.setLayout(affairsViewLayout);
        affairsViewLayout.setHorizontalGroup(
            affairsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        affairsViewLayout.setVerticalGroup(
            affairsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        attendanceView.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                attendanceViewMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout attendanceViewLayout = new javax.swing.GroupLayout(attendanceView);
        attendanceView.setLayout(attendanceViewLayout);
        attendanceViewLayout.setHorizontalGroup(
            attendanceViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        attendanceViewLayout.setVerticalGroup(
            attendanceViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        salaryView.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                salaryViewMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout salaryViewLayout = new javax.swing.GroupLayout(salaryView);
        salaryView.setLayout(salaryViewLayout);
        salaryViewLayout.setHorizontalGroup(
            salaryViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        salaryViewLayout.setVerticalGroup(
            salaryViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        reportsView.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                reportsViewMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout reportsViewLayout = new javax.swing.GroupLayout(reportsView);
        reportsView.setLayout(reportsViewLayout);
        reportsViewLayout.setHorizontalGroup(
            reportsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        reportsViewLayout.setVerticalGroup(
            reportsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        hierarchyView.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                hierarchyViewMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout hierarchyViewLayout = new javax.swing.GroupLayout(hierarchyView);
        hierarchyView.setLayout(hierarchyViewLayout);
        hierarchyViewLayout.setHorizontalGroup(
            hierarchyViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        hierarchyViewLayout.setVerticalGroup(
            hierarchyViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        adminView.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                adminViewMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout adminViewLayout = new javax.swing.GroupLayout(adminView);
        adminView.setLayout(adminViewLayout);
        adminViewLayout.setHorizontalGroup(
            adminViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        adminViewLayout.setVerticalGroup(
            adminViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        logoutView.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                logoutViewMouseMoved(evt);
            }
        });
        logoutView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutViewMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout logoutViewLayout = new javax.swing.GroupLayout(logoutView);
        logoutView.setLayout(logoutViewLayout);
        logoutViewLayout.setHorizontalGroup(
            logoutViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        logoutViewLayout.setVerticalGroup(
            logoutViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        logoView.setBackground(new java.awt.Color(234, 233, 231));
        logoView.setMaximumSize(new java.awt.Dimension(359, 191));

        javax.swing.GroupLayout logoViewLayout = new javax.swing.GroupLayout(logoView);
        logoView.setLayout(logoViewLayout);
        logoViewLayout.setHorizontalGroup(
            logoViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        logoViewLayout.setVerticalGroup(
            logoViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        jLabel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salaryView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(adminView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attendanceView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hierarchyView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(affairsView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settingsView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportsView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(affairsView, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(settingsView, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attendanceView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salaryView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reportsView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hierarchyView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void affairsViewMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_affairsViewMouseClicked
    {//GEN-HEADEREND:event_affairsViewMouseClicked
        comObj.showForm(new HREmployeesAffiars(), this);
    }//GEN-LAST:event_affairsViewMouseClicked

    private void affairsViewMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_affairsViewMouseMoved
    {//GEN-HEADEREND:event_affairsViewMouseMoved
        affairsView.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_affairsViewMouseMoved

    private void salaryViewMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_salaryViewMouseMoved
    {//GEN-HEADEREND:event_salaryViewMouseMoved
        salaryView.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_salaryViewMouseMoved

    private void logoutViewMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_logoutViewMouseMoved
    {//GEN-HEADEREND:event_logoutViewMouseMoved
        logoutView.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_logoutViewMouseMoved

    private void logoutViewMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_logoutViewMouseClicked
    {//GEN-HEADEREND:event_logoutViewMouseClicked
        try {
            comObj.showForm(new HRLogin(), this);
        } catch (IOException ex) {
            System.out.println("Exception in " + MainParts.class.getName() + ":" + ex.getMessage());
        }
    }//GEN-LAST:event_logoutViewMouseClicked

    private void attendanceViewMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceViewMouseMoved
        attendanceView.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_attendanceViewMouseMoved

    private void adminViewMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminViewMouseMoved
        adminView.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_adminViewMouseMoved

    private void hierarchyViewMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hierarchyViewMouseMoved
        hierarchyView.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_hierarchyViewMouseMoved

    private void reportsViewMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsViewMouseMoved
        reportsView.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_reportsViewMouseMoved

    private void settingsViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsViewMouseClicked
        try {
            comObj.showForm(new HRMS_General(), this);
        } catch (IOException ex) {
            System.out.println("Exception in " + MainParts.class.getName() + ":" + ex.getMessage());
        } catch (OrganDaoException ex)
        {
            Logger.getLogger(MainParts.class.getName()).log(Level.SEVERE, null, ex);
        } catch (AccidentTypesDaoException ex)
        {
            Logger.getLogger(MainParts.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DiseaseTypesDaoException ex)
        {
            Logger.getLogger(MainParts.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DiseasesDaoException ex)
        {
            Logger.getLogger(MainParts.class.getName()).log(Level.SEVERE, null, ex);
        } catch (HospitalsDaoException ex)
        {
            Logger.getLogger(MainParts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_settingsViewMouseClicked

    private void settingsViewMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsViewMouseMoved
        settingsView.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_settingsViewMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainParts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new MainParts().setVisible(true);
            } catch (IOException ex) {
                System.out.println("Exception in " + MainParts.class.getName() + ":" + ex.getMessage());

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXImageView adminView;
    private org.jdesktop.swingx.JXImageView affairsView;
    private org.jdesktop.swingx.JXImageView attendanceView;
    private org.jdesktop.swingx.JXImageView hierarchyView;
    private javax.swing.JLabel jLabel1;
    private org.jdesktop.swingx.JXImageView logoView;
    private org.jdesktop.swingx.JXImageView logoutView;
    private org.jdesktop.swingx.JXImageView reportsView;
    private org.jdesktop.swingx.JXImageView salaryView;
    private org.jdesktop.swingx.JXImageView settingsView;
    // End of variables declaration//GEN-END:variables
}
