/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.jdbc;

import senior.hrms.emps.dao.*;
import senior.hrms.emps.factory.*;
import senior.hrms.emps.dto.*;
import senior.hrms.emps.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class BusLineAreasDaoImpl extends AbstractDAO implements BusLineAreasDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT BUS_LINE_AREA_ID, BUS_LINE_AREA_NAME, BUS_LINE_ID FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( BUS_LINE_AREA_ID, BUS_LINE_AREA_NAME, BUS_LINE_ID ) VALUES ( ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET BUS_LINE_AREA_ID = ?, BUS_LINE_AREA_NAME = ?, BUS_LINE_ID = ? WHERE BUS_LINE_AREA_ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE BUS_LINE_AREA_ID = ?";

	/** 
	 * Index of column BUS_LINE_AREA_ID
	 */
	protected static final int COLUMN_BUS_LINE_AREA_ID = 1;

	/** 
	 * Index of column BUS_LINE_AREA_NAME
	 */
	protected static final int COLUMN_BUS_LINE_AREA_NAME = 2;

	/** 
	 * Index of column BUS_LINE_ID
	 */
	protected static final int COLUMN_BUS_LINE_ID = 3;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 3;

	/** 
	 * Index of primary-key column BUS_LINE_AREA_ID
	 */
	protected static final int PK_COLUMN_BUS_LINE_AREA_ID = 1;

	/** 
	 * Inserts a new row in the BUS_LINE_AREAS table.
	 */
	public BusLineAreasPk insert(BusLineAreas dto) throws BusLineAreasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setInt( index++, dto.getBusLineAreaId() );
			stmt.setString( index++, dto.getBusLineAreaName() );
			stmt.setInt( index++, dto.getBusLineId() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new BusLineAreasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the BUS_LINE_AREAS table.
	 */
	public void update(BusLineAreasPk pk, BusLineAreas dto) throws BusLineAreasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getBusLineAreaId() );
			stmt.setString( index++, dto.getBusLineAreaName() );
			stmt.setInt( index++, dto.getBusLineId() );
			stmt.setInt( 4, pk.getBusLineAreaId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new BusLineAreasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the BUS_LINE_AREAS table.
	 */
	public void delete(BusLineAreasPk pk) throws BusLineAreasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getBusLineAreaId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new BusLineAreasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the BUS_LINE_AREAS table that matches the specified primary-key value.
	 */
	public BusLineAreas findByPrimaryKey(BusLineAreasPk pk) throws BusLineAreasDaoException
	{
		return findByPrimaryKey( pk.getBusLineAreaId() );
	}

	/** 
	 * Returns all rows from the BUS_LINE_AREAS table that match the criteria 'BUS_LINE_AREA_ID = :busLineAreaId'.
	 */
	public BusLineAreas findByPrimaryKey(int busLineAreaId) throws BusLineAreasDaoException
	{
		BusLineAreas ret[] = findByDynamicSelect( SQL_SELECT + " WHERE BUS_LINE_AREA_ID = ?", new Object[] {  new Integer(busLineAreaId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the BUS_LINE_AREAS table that match the criteria ''.
	 */
	public BusLineAreas[] findAll() throws BusLineAreasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY BUS_LINE_AREA_ID", null );
	}

	/** 
	 * Returns all rows from the BUS_LINE_AREAS table that match the criteria 'BUS_LINE_ID = :busLineId'.
	 */
	public BusLineAreas[] findByBusLines(int busLineId) throws BusLineAreasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE BUS_LINE_ID = ?", new Object[] {  new Integer(busLineId) } );
	}

	/** 
	 * Returns all rows from the BUS_LINE_AREAS table that match the criteria 'BUS_LINE_AREA_ID = :busLineAreaId'.
	 */
	public BusLineAreas[] findWhereBusLineAreaIdEquals(int busLineAreaId) throws BusLineAreasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE BUS_LINE_AREA_ID = ? ORDER BY BUS_LINE_AREA_ID", new Object[] {  new Integer(busLineAreaId) } );
	}

	/** 
	 * Returns all rows from the BUS_LINE_AREAS table that match the criteria 'BUS_LINE_AREA_NAME = :busLineAreaName'.
	 */
	public BusLineAreas[] findWhereBusLineAreaNameEquals(String busLineAreaName) throws BusLineAreasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE BUS_LINE_AREA_NAME = ? ORDER BY BUS_LINE_AREA_NAME", new Object[] { busLineAreaName } );
	}

	/** 
	 * Returns all rows from the BUS_LINE_AREAS table that match the criteria 'BUS_LINE_ID = :busLineId'.
	 */
	public BusLineAreas[] findWhereBusLineIdEquals(int busLineId) throws BusLineAreasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE BUS_LINE_ID = ? ORDER BY BUS_LINE_ID", new Object[] {  new Integer(busLineId) } );
	}

	/**
	 * Method 'BusLineAreasDaoImpl'
	 * 
	 */
	public BusLineAreasDaoImpl()
	{
	}

	/**
	 * Method 'BusLineAreasDaoImpl'
	 * 
	 * @param userConn
	 */
	public BusLineAreasDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "HRMS.BUS_LINE_AREAS";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected BusLineAreas fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			BusLineAreas dto = new BusLineAreas();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected BusLineAreas[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			BusLineAreas dto = new BusLineAreas();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		BusLineAreas ret[] = new BusLineAreas[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(BusLineAreas dto, ResultSet rs) throws SQLException
	{
		dto.setBusLineAreaId( rs.getInt( COLUMN_BUS_LINE_AREA_ID ) );
		dto.setBusLineAreaName( rs.getString( COLUMN_BUS_LINE_AREA_NAME ) );
		dto.setBusLineId( rs.getInt( COLUMN_BUS_LINE_ID ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(BusLineAreas dto)
	{
	}

	/** 
	 * Returns all rows from the BUS_LINE_AREAS table that match the specified arbitrary SQL statement
	 */
	public BusLineAreas[] findByDynamicSelect(String sql, Object[] sqlParams) throws BusLineAreasDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new BusLineAreasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the BUS_LINE_AREAS table that match the specified arbitrary SQL statement
	 */
	public BusLineAreas[] findByDynamicWhere(String sql, Object[] sqlParams) throws BusLineAreasDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new BusLineAreasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
