/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.jdbc;

import senior.hrms.emps.dao.*;
import senior.hrms.emps.factory.*;
import senior.hrms.emps.dto.*;
import senior.hrms.emps.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class DiseasesDaoImpl extends AbstractDAO implements DiseasesDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT DISEASE_ID, DISEASE_NAME, RESULT, DISEASE_TYPE_ID FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( DISEASE_ID, DISEASE_NAME, RESULT, DISEASE_TYPE_ID ) VALUES ( ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET DISEASE_ID = ?, DISEASE_NAME = ?, RESULT = ?, DISEASE_TYPE_ID = ? WHERE DISEASE_ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE DISEASE_ID = ?";

	/** 
	 * Index of column DISEASE_ID
	 */
	protected static final int COLUMN_DISEASE_ID = 1;

	/** 
	 * Index of column DISEASE_NAME
	 */
	protected static final int COLUMN_DISEASE_NAME = 2;

	/** 
	 * Index of column RESULT
	 */
	protected static final int COLUMN_RESULT = 3;

	/** 
	 * Index of column DISEASE_TYPE_ID
	 */
	protected static final int COLUMN_DISEASE_TYPE_ID = 4;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 4;

	/** 
	 * Index of primary-key column DISEASE_ID
	 */
	protected static final int PK_COLUMN_DISEASE_ID = 1;

	/** 
	 * Inserts a new row in the DISEASES table.
	 */
	public DiseasesPk insert(Diseases dto) throws DiseasesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setInt( index++, dto.getDiseaseId() );
			stmt.setString( index++, dto.getDiseaseName() );
			stmt.setString( index++, dto.getResult() );
			if (dto.isDiseaseTypeIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getDiseaseTypeId() );
			}
		
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DiseasesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the DISEASES table.
	 */
	public void update(DiseasesPk pk, Diseases dto) throws DiseasesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getDiseaseId() );
			stmt.setString( index++, dto.getDiseaseName() );
			stmt.setString( index++, dto.getResult() );
			if (dto.isDiseaseTypeIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getDiseaseTypeId() );
			}
		
			stmt.setInt( 5, pk.getDiseaseId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DiseasesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the DISEASES table.
	 */
	public void delete(DiseasesPk pk) throws DiseasesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getDiseaseId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DiseasesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the DISEASES table that matches the specified primary-key value.
	 */
	public Diseases findByPrimaryKey(DiseasesPk pk) throws DiseasesDaoException
	{
		return findByPrimaryKey( pk.getDiseaseId() );
	}

	/** 
	 * Returns all rows from the DISEASES table that match the criteria 'DISEASE_ID = :diseaseId'.
	 */
	public Diseases findByPrimaryKey(int diseaseId) throws DiseasesDaoException
	{
		Diseases ret[] = findByDynamicSelect( SQL_SELECT + " WHERE DISEASE_ID = ?", new Object[] {  new Integer(diseaseId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the DISEASES table that match the criteria ''.
	 */
	public Diseases[] findAll() throws DiseasesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY DISEASE_ID", null );
	}

	/** 
	 * Returns all rows from the DISEASES table that match the criteria 'DISEASE_TYPE_ID = :diseaseTypeId'.
	 */
	public Diseases[] findByDiseaseTypes(int diseaseTypeId) throws DiseasesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE DISEASE_TYPE_ID = ?", new Object[] {  new Integer(diseaseTypeId) } );
	}

	/** 
	 * Returns all rows from the DISEASES table that match the criteria 'DISEASE_ID = :diseaseId'.
	 */
	public Diseases[] findWhereDiseaseIdEquals(int diseaseId) throws DiseasesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE DISEASE_ID = ? ORDER BY DISEASE_ID", new Object[] {  new Integer(diseaseId) } );
	}

	/** 
	 * Returns all rows from the DISEASES table that match the criteria 'DISEASE_NAME = :diseaseName'.
	 */
	public Diseases[] findWhereDiseaseNameEquals(String diseaseName) throws DiseasesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE DISEASE_NAME = ? ORDER BY DISEASE_NAME", new Object[] { diseaseName } );
	}

	/** 
	 * Returns all rows from the DISEASES table that match the criteria 'RESULT = :result'.
	 */
	public Diseases[] findWhereResultEquals(String result) throws DiseasesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE RESULT = ? ORDER BY RESULT", new Object[] { result } );
	}

	/** 
	 * Returns all rows from the DISEASES table that match the criteria 'DISEASE_TYPE_ID = :diseaseTypeId'.
	 */
	public Diseases[] findWhereDiseaseTypeIdEquals(int diseaseTypeId) throws DiseasesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE DISEASE_TYPE_ID = ? ORDER BY DISEASE_TYPE_ID", new Object[] {  new Integer(diseaseTypeId) } );
	}

	/**
	 * Method 'DiseasesDaoImpl'
	 * 
	 */
	public DiseasesDaoImpl()
	{
	}

	/**
	 * Method 'DiseasesDaoImpl'
	 * 
	 * @param userConn
	 */
	public DiseasesDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "HRMS.DISEASES";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Diseases fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Diseases dto = new Diseases();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Diseases[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Diseases dto = new Diseases();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Diseases ret[] = new Diseases[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Diseases dto, ResultSet rs) throws SQLException
	{
		dto.setDiseaseId( rs.getInt( COLUMN_DISEASE_ID ) );
		dto.setDiseaseName( rs.getString( COLUMN_DISEASE_NAME ) );
		dto.setResult( rs.getString( COLUMN_RESULT ) );
		dto.setDiseaseTypeId( rs.getInt( COLUMN_DISEASE_TYPE_ID ) );
		if (rs.wasNull()) {
			dto.setDiseaseTypeIdNull( true );
		}
		
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Diseases dto)
	{
	}

	/** 
	 * Returns all rows from the DISEASES table that match the specified arbitrary SQL statement
	 */
	public Diseases[] findByDynamicSelect(String sql, Object[] sqlParams) throws DiseasesDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DiseasesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the DISEASES table that match the specified arbitrary SQL statement
	 */
	public Diseases[] findByDynamicWhere(String sql, Object[] sqlParams) throws DiseasesDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DiseasesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
