/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.jdbc;

import senior.hrms.emps.dao.*;
import senior.hrms.emps.factory.*;
import senior.hrms.emps.dto.*;
import senior.hrms.emps.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class EmpEvaluationDaoImpl extends AbstractDAO implements EmpEvaluationDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT EMP_EVALUATION_ID, EMPLOYEE_ID, EVALUATION_ITEM_ID, EVALUATION_DEGERE_ID, DEGREE_PERCENTAGE, EVALUATED_BY_EMP_ID, FINANCIAL_YEAR_ID FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( EMP_EVALUATION_ID, EMPLOYEE_ID, EVALUATION_ITEM_ID, EVALUATION_DEGERE_ID, DEGREE_PERCENTAGE, EVALUATED_BY_EMP_ID, FINANCIAL_YEAR_ID ) VALUES ( ?, ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET EMP_EVALUATION_ID = ?, EMPLOYEE_ID = ?, EVALUATION_ITEM_ID = ?, EVALUATION_DEGERE_ID = ?, DEGREE_PERCENTAGE = ?, EVALUATED_BY_EMP_ID = ?, FINANCIAL_YEAR_ID = ? WHERE EMP_EVALUATION_ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE EMP_EVALUATION_ID = ?";

	/** 
	 * Index of column EMP_EVALUATION_ID
	 */
	protected static final int COLUMN_EMP_EVALUATION_ID = 1;

	/** 
	 * Index of column EMPLOYEE_ID
	 */
	protected static final int COLUMN_EMPLOYEE_ID = 2;

	/** 
	 * Index of column EVALUATION_ITEM_ID
	 */
	protected static final int COLUMN_EVALUATION_ITEM_ID = 3;

	/** 
	 * Index of column EVALUATION_DEGERE_ID
	 */
	protected static final int COLUMN_EVALUATION_DEGERE_ID = 4;

	/** 
	 * Index of column DEGREE_PERCENTAGE
	 */
	protected static final int COLUMN_DEGREE_PERCENTAGE = 5;

	/** 
	 * Index of column EVALUATED_BY_EMP_ID
	 */
	protected static final int COLUMN_EVALUATED_BY_EMP_ID = 6;

	/** 
	 * Index of column FINANCIAL_YEAR_ID
	 */
	protected static final int COLUMN_FINANCIAL_YEAR_ID = 7;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 7;

	/** 
	 * Index of primary-key column EMP_EVALUATION_ID
	 */
	protected static final int PK_COLUMN_EMP_EVALUATION_ID = 1;

	/** 
	 * Inserts a new row in the EMP_EVALUATION table.
	 */
	public EmpEvaluationPk insert(EmpEvaluation dto) throws EmpEvaluationDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setInt( index++, dto.getEmpEvaluationId() );
			stmt.setInt( index++, dto.getEmployeeId() );
			stmt.setInt( index++, dto.getEvaluationItemId() );
			stmt.setInt( index++, dto.getEvaluationDegereId() );
			if (dto.isDegreePercentageNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getDegreePercentage() );
			}
		
			stmt.setInt( index++, dto.getEvaluatedByEmpId() );
			stmt.setInt( index++, dto.getFinancialYearId() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EmpEvaluationDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the EMP_EVALUATION table.
	 */
	public void update(EmpEvaluationPk pk, EmpEvaluation dto) throws EmpEvaluationDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getEmpEvaluationId() );
			stmt.setInt( index++, dto.getEmployeeId() );
			stmt.setInt( index++, dto.getEvaluationItemId() );
			stmt.setInt( index++, dto.getEvaluationDegereId() );
			if (dto.isDegreePercentageNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getDegreePercentage() );
			}
		
			stmt.setInt( index++, dto.getEvaluatedByEmpId() );
			stmt.setInt( index++, dto.getFinancialYearId() );
			stmt.setInt( 8, pk.getEmpEvaluationId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EmpEvaluationDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the EMP_EVALUATION table.
	 */
	public void delete(EmpEvaluationPk pk) throws EmpEvaluationDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getEmpEvaluationId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EmpEvaluationDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the EMP_EVALUATION table that matches the specified primary-key value.
	 */
	public EmpEvaluation findByPrimaryKey(EmpEvaluationPk pk) throws EmpEvaluationDaoException
	{
		return findByPrimaryKey( pk.getEmpEvaluationId() );
	}

	/** 
	 * Returns all rows from the EMP_EVALUATION table that match the criteria 'EMP_EVALUATION_ID = :empEvaluationId'.
	 */
	public EmpEvaluation findByPrimaryKey(int empEvaluationId) throws EmpEvaluationDaoException
	{
		EmpEvaluation ret[] = findByDynamicSelect( SQL_SELECT + " WHERE EMP_EVALUATION_ID = ?", new Object[] {  new Integer(empEvaluationId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the EMP_EVALUATION table that match the criteria ''.
	 */
	public EmpEvaluation[] findAll() throws EmpEvaluationDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY EMP_EVALUATION_ID", null );
	}

	/** 
	 * Returns all rows from the EMP_EVALUATION table that match the criteria 'EMPLOYEE_ID = :employeeId'.
	 */
	public EmpEvaluation[] findByEmployees(int employeeId) throws EmpEvaluationDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE EMPLOYEE_ID = ?", new Object[] {  new Integer(employeeId) } );
	}

	
	
	
	
	
	
	
	
	/** 
	 * Returns all rows from the EMP_EVALUATION table that match the criteria 'FINANCIAL_YEAR_ID = :financialYearId'.
	 */
	public EmpEvaluation[] findByFinancialYears(int financialYearId) throws EmpEvaluationDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE FINANCIAL_YEAR_ID = ?", new Object[] {  new Integer(financialYearId) } );
	}
	
	
	
	
	
	
	
	
	
	/** 
	 * Returns all rows from the EMP_EVALUATION table that match the criteria 'EVALUATION_DEGERE_ID = :evaluationDegereId'.
	 */
	public EmpEvaluation[] findByEvaluationsDegree(int evaluationDegereId) throws EmpEvaluationDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE EVALUATION_DEGERE_ID = ?", new Object[] {  new Integer(evaluationDegereId) } );
	}

	/** 
	 * Returns all rows from the EMP_EVALUATION table that match the criteria 'EVALUATION_ITEM_ID = :evaluationItemId'.
	 */
	public EmpEvaluation[] findByEvaluationItem(int evaluationItemId) throws EmpEvaluationDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE EVALUATION_ITEM_ID = ?", new Object[] {  new Integer(evaluationItemId) } );
	}

	/** 
	 * Returns all rows from the EMP_EVALUATION table that match the criteria 'EMP_EVALUATION_ID = :empEvaluationId'.
	 */
	public EmpEvaluation[] findWhereEmpEvaluationIdEquals(int empEvaluationId) throws EmpEvaluationDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE EMP_EVALUATION_ID = ? ORDER BY EMP_EVALUATION_ID", new Object[] {  new Integer(empEvaluationId) } );
	}

	/** 
	 * Returns all rows from the EMP_EVALUATION table that match the criteria 'EMPLOYEE_ID = :employeeId'.
	 */
	public EmpEvaluation[] findWhereEmployeeIdEquals(int employeeId) throws EmpEvaluationDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE EMPLOYEE_ID = ? ORDER BY EMPLOYEE_ID", new Object[] {  new Integer(employeeId) } );
	}

	/** 
	 * Returns all rows from the EMP_EVALUATION table that match the criteria 'EVALUATION_ITEM_ID = :evaluationItemId'.
	 */
	public EmpEvaluation[] findWhereEvaluationItemIdEquals(int evaluationItemId) throws EmpEvaluationDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE EVALUATION_ITEM_ID = ? ORDER BY EVALUATION_ITEM_ID", new Object[] {  new Integer(evaluationItemId) } );
	}

	/** 
	 * Returns all rows from the EMP_EVALUATION table that match the criteria 'EVALUATION_DEGERE_ID = :evaluationDegereId'.
	 */
	public EmpEvaluation[] findWhereEvaluationDegereIdEquals(int evaluationDegereId) throws EmpEvaluationDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE EVALUATION_DEGERE_ID = ? ORDER BY EVALUATION_DEGERE_ID", new Object[] {  new Integer(evaluationDegereId) } );
	}

	/** 
	 * Returns all rows from the EMP_EVALUATION table that match the criteria 'DEGREE_PERCENTAGE = :degreePercentage'.
	 */
	public EmpEvaluation[] findWhereDegreePercentageEquals(int degreePercentage) throws EmpEvaluationDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE DEGREE_PERCENTAGE = ? ORDER BY DEGREE_PERCENTAGE", new Object[] {  new Integer(degreePercentage) } );
	}

	/** 
	 * Returns all rows from the EMP_EVALUATION table that match the criteria 'EVALUATED_BY_EMP_ID = :evaluatedByEmpId'.
	 */
	public EmpEvaluation[] findWhereEvaluatedByEmpIdEquals(int evaluatedByEmpId) throws EmpEvaluationDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE EVALUATED_BY_EMP_ID = ? ORDER BY EVALUATED_BY_EMP_ID", new Object[] {  new Integer(evaluatedByEmpId) } );
	}

	/** 
	 * Returns all rows from the EMP_EVALUATION table that match the criteria 'FINANCIAL_YEAR_ID = :financialYearId'.
	 */
	public EmpEvaluation[] findWhereFinancialYearIdEquals(int financialYearId) throws EmpEvaluationDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE FINANCIAL_YEAR_ID = ? ORDER BY FINANCIAL_YEAR_ID", new Object[] {  new Integer(financialYearId) } );
	}

	/**
	 * Method 'EmpEvaluationDaoImpl'
	 * 
	 */
	public EmpEvaluationDaoImpl()
	{
	}

	/**
	 * Method 'EmpEvaluationDaoImpl'
	 * 
	 * @param userConn
	 */
	public EmpEvaluationDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "HRMS.EMP_EVALUATION";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected EmpEvaluation fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			EmpEvaluation dto = new EmpEvaluation();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected EmpEvaluation[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			EmpEvaluation dto = new EmpEvaluation();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		EmpEvaluation ret[] = new EmpEvaluation[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(EmpEvaluation dto, ResultSet rs) throws SQLException
	{
		dto.setEmpEvaluationId( rs.getInt( COLUMN_EMP_EVALUATION_ID ) );
		dto.setEmployeeId( rs.getInt( COLUMN_EMPLOYEE_ID ) );
		dto.setEvaluationItemId( rs.getInt( COLUMN_EVALUATION_ITEM_ID ) );
		dto.setEvaluationDegereId( rs.getInt( COLUMN_EVALUATION_DEGERE_ID ) );
		dto.setDegreePercentage( rs.getInt( COLUMN_DEGREE_PERCENTAGE ) );
		if (rs.wasNull()) {
			dto.setDegreePercentageNull( true );
		}
		
		dto.setEvaluatedByEmpId( rs.getInt( COLUMN_EVALUATED_BY_EMP_ID ) );
		dto.setFinancialYearId( rs.getInt( COLUMN_FINANCIAL_YEAR_ID ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(EmpEvaluation dto)
	{
	}

	/** 
	 * Returns all rows from the EMP_EVALUATION table that match the specified arbitrary SQL statement
	 */
	public EmpEvaluation[] findByDynamicSelect(String sql, Object[] sqlParams) throws EmpEvaluationDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EmpEvaluationDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the EMP_EVALUATION table that match the specified arbitrary SQL statement
	 */
	public EmpEvaluation[] findByDynamicWhere(String sql, Object[] sqlParams) throws EmpEvaluationDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EmpEvaluationDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
