/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.jdbc;

import senior.hrms.emps.dao.*;
import senior.hrms.emps.factory.*;
import senior.hrms.emps.dto.*;
import senior.hrms.emps.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class EmpHealthCareDaoImpl extends AbstractDAO implements EmpHealthCareDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT HEALTH_CARE_ID, CARD_CODE FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( HEALTH_CARE_ID, CARD_CODE ) VALUES ( ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET HEALTH_CARE_ID = ?, CARD_CODE = ? WHERE HEALTH_CARE_ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE HEALTH_CARE_ID = ?";

	/** 
	 * Index of column HEALTH_CARE_ID
	 */
	protected static final int COLUMN_HEALTH_CARE_ID = 1;

	/** 
	 * Index of column CARD_CODE
	 */
	protected static final int COLUMN_CARD_CODE = 2;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 2;

	/** 
	 * Index of primary-key column HEALTH_CARE_ID
	 */
	protected static final int PK_COLUMN_HEALTH_CARE_ID = 1;

	/** 
	 * Inserts a new row in the EMP_HEALTH_CARE table.
	 */
	public EmpHealthCarePk insert(EmpHealthCare dto) throws EmpHealthCareDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setInt( index++, dto.getHealthCareId() );
			stmt.setString( index++, dto.getCardCode() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EmpHealthCareDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the EMP_HEALTH_CARE table.
	 */
	public void update(EmpHealthCarePk pk, EmpHealthCare dto) throws EmpHealthCareDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getHealthCareId() );
			stmt.setString( index++, dto.getCardCode() );
			stmt.setInt( 3, pk.getHealthCareId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EmpHealthCareDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the EMP_HEALTH_CARE table.
	 */
	public void delete(EmpHealthCarePk pk) throws EmpHealthCareDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getHealthCareId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EmpHealthCareDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the EMP_HEALTH_CARE table that matches the specified primary-key value.
	 */
	public EmpHealthCare findByPrimaryKey(EmpHealthCarePk pk) throws EmpHealthCareDaoException
	{
		return findByPrimaryKey( pk.getHealthCareId() );
	}

	/** 
	 * Returns all rows from the EMP_HEALTH_CARE table that match the criteria 'HEALTH_CARE_ID = :healthCareId'.
	 */
	public EmpHealthCare findByPrimaryKey(int healthCareId) throws EmpHealthCareDaoException
	{
		EmpHealthCare ret[] = findByDynamicSelect( SQL_SELECT + " WHERE HEALTH_CARE_ID = ?", new Object[] {  new Integer(healthCareId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the EMP_HEALTH_CARE table that match the criteria ''.
	 */
	public EmpHealthCare[] findAll() throws EmpHealthCareDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY HEALTH_CARE_ID", null );
	}

	/** 
	 * Returns all rows from the EMP_HEALTH_CARE table that match the criteria 'HEALTH_CARE_ID = :healthCareId'.
	 */
	public EmpHealthCare[] findWhereHealthCareIdEquals(int healthCareId) throws EmpHealthCareDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE HEALTH_CARE_ID = ? ORDER BY HEALTH_CARE_ID", new Object[] {  new Integer(healthCareId) } );
	}

	/** 
	 * Returns all rows from the EMP_HEALTH_CARE table that match the criteria 'CARD_CODE = :cardCode'.
	 */
	public EmpHealthCare[] findWhereCardCodeEquals(String cardCode) throws EmpHealthCareDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CARD_CODE = ? ORDER BY CARD_CODE", new Object[] { cardCode } );
	}

	/**
	 * Method 'EmpHealthCareDaoImpl'
	 * 
	 */
	public EmpHealthCareDaoImpl()
	{
	}

	/**
	 * Method 'EmpHealthCareDaoImpl'
	 * 
	 * @param userConn
	 */
	public EmpHealthCareDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "HRMS.EMP_HEALTH_CARE";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected EmpHealthCare fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			EmpHealthCare dto = new EmpHealthCare();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected EmpHealthCare[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			EmpHealthCare dto = new EmpHealthCare();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		EmpHealthCare ret[] = new EmpHealthCare[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(EmpHealthCare dto, ResultSet rs) throws SQLException
	{
		dto.setHealthCareId( rs.getInt( COLUMN_HEALTH_CARE_ID ) );
		dto.setCardCode( rs.getString( COLUMN_CARD_CODE ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(EmpHealthCare dto)
	{
	}

	/** 
	 * Returns all rows from the EMP_HEALTH_CARE table that match the specified arbitrary SQL statement
	 */
	public EmpHealthCare[] findByDynamicSelect(String sql, Object[] sqlParams) throws EmpHealthCareDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EmpHealthCareDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the EMP_HEALTH_CARE table that match the specified arbitrary SQL statement
	 */
	public EmpHealthCare[] findByDynamicWhere(String sql, Object[] sqlParams) throws EmpHealthCareDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EmpHealthCareDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
