/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.jdbc;

import senior.hrms.emps.dao.*;
import senior.hrms.emps.factory.*;
import senior.hrms.emps.dto.*;
import senior.hrms.emps.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class EmpSickLeaveDaoImpl extends AbstractDAO implements EmpSickLeaveDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT EMP_SICK_LEAVE_ID, EMPLOYEE_ID, DISEASE_ID, HOSPITAL_ID, EMP_VACATION_ID, HOSPITAL_REPORT_IMAGE FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( EMP_SICK_LEAVE_ID, EMPLOYEE_ID, DISEASE_ID, HOSPITAL_ID, EMP_VACATION_ID, HOSPITAL_REPORT_IMAGE ) VALUES ( ?, ?, ?, ?, ?, EMPTY_BLOB() )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET EMP_SICK_LEAVE_ID = ?, EMPLOYEE_ID = ?, DISEASE_ID = ?, HOSPITAL_ID = ?, EMP_VACATION_ID = ?, HOSPITAL_REPORT_IMAGE = EMPTY_BLOB() WHERE EMP_SICK_LEAVE_ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE EMP_SICK_LEAVE_ID = ?";

	/** 
	 * Index of column EMP_SICK_LEAVE_ID
	 */
	protected static final int COLUMN_EMP_SICK_LEAVE_ID = 1;

	/** 
	 * Index of column EMPLOYEE_ID
	 */
	protected static final int COLUMN_EMPLOYEE_ID = 2;

	/** 
	 * Index of column DISEASE_ID
	 */
	protected static final int COLUMN_DISEASE_ID = 3;

	/** 
	 * Index of column HOSPITAL_ID
	 */
	protected static final int COLUMN_HOSPITAL_ID = 4;

	/** 
	 * Index of column EMP_VACATION_ID
	 */
	protected static final int COLUMN_EMP_VACATION_ID = 5;

	/** 
	 * Index of column HOSPITAL_REPORT_IMAGE
	 */
	protected static final int COLUMN_HOSPITAL_REPORT_IMAGE = 6;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 6;

	/** 
	 * Index of primary-key column EMP_SICK_LEAVE_ID
	 */
	protected static final int PK_COLUMN_EMP_SICK_LEAVE_ID = 1;

	/** 
	 * Inserts a new row in the EMP_SICK_LEAVE table.
	 */
	public EmpSickLeavePk insert(EmpSickLeave dto) throws EmpSickLeaveDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setInt( index++, dto.getEmpSickLeaveId() );
			stmt.setInt( index++, dto.getEmployeeId() );
			stmt.setInt( index++, dto.getDiseaseId() );
			stmt.setInt( index++, dto.getHospitalId() );
			stmt.setLong( index++, dto.getEmpVacationId() );
			// no need to bind value for LOB column
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EmpSickLeaveDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the EMP_SICK_LEAVE table.
	 */
	public void update(EmpSickLeavePk pk, EmpSickLeave dto) throws EmpSickLeaveDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getEmpSickLeaveId() );
			stmt.setInt( index++, dto.getEmployeeId() );
			stmt.setInt( index++, dto.getDiseaseId() );
			stmt.setInt( index++, dto.getHospitalId() );
			stmt.setLong( index++, dto.getEmpVacationId() );
			// no need to bind value for LOB column
			stmt.setInt( 6, pk.getEmpSickLeaveId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EmpSickLeaveDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the EMP_SICK_LEAVE table.
	 */
	public void delete(EmpSickLeavePk pk) throws EmpSickLeaveDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getEmpSickLeaveId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EmpSickLeaveDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the EMP_SICK_LEAVE table that matches the specified primary-key value.
	 */
	public EmpSickLeave findByPrimaryKey(EmpSickLeavePk pk) throws EmpSickLeaveDaoException
	{
		return findByPrimaryKey( pk.getEmpSickLeaveId() );
	}

	/** 
	 * Returns all rows from the EMP_SICK_LEAVE table that match the criteria 'EMP_SICK_LEAVE_ID = :empSickLeaveId'.
	 */
	public EmpSickLeave findByPrimaryKey(int empSickLeaveId) throws EmpSickLeaveDaoException
	{
		EmpSickLeave ret[] = findByDynamicSelect( SQL_SELECT + " WHERE EMP_SICK_LEAVE_ID = ?", new Object[] {  new Integer(empSickLeaveId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the EMP_SICK_LEAVE table that match the criteria ''.
	 */
	public EmpSickLeave[] findAll() throws EmpSickLeaveDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY EMP_SICK_LEAVE_ID", null );
	}

	/** 
	 * Returns all rows from the EMP_SICK_LEAVE table that match the criteria 'DISEASE_ID = :diseaseId'.
	 */
	public EmpSickLeave[] findByDiseases(int diseaseId) throws EmpSickLeaveDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE DISEASE_ID = ?", new Object[] {  new Integer(diseaseId) } );
	}

	/** 
	 * Returns all rows from the EMP_SICK_LEAVE table that match the criteria 'EMPLOYEE_ID = :employeeId'.
	 */
	public EmpSickLeave[] findByEmployees(int employeeId) throws EmpSickLeaveDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE EMPLOYEE_ID = ?", new Object[] {  new Integer(employeeId) } );
	}

	/** 
	 * Returns all rows from the EMP_SICK_LEAVE table that match the criteria 'EMP_VACATION_ID = :empVacationId'.
	 */
	public EmpSickLeave[] findByEmpVacations(long empVacationId) throws EmpSickLeaveDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE EMP_VACATION_ID = ?", new Object[] {  new Long(empVacationId) } );
	}

	/** 
	 * Returns all rows from the EMP_SICK_LEAVE table that match the criteria 'HOSPITAL_ID = :hospitalId'.
	 */
	public EmpSickLeave[] findByHospitals(int hospitalId) throws EmpSickLeaveDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE HOSPITAL_ID = ?", new Object[] {  new Integer(hospitalId) } );
	}

	/** 
	 * Returns all rows from the EMP_SICK_LEAVE table that match the criteria 'EMP_SICK_LEAVE_ID = :empSickLeaveId'.
	 */
	public EmpSickLeave[] findWhereEmpSickLeaveIdEquals(int empSickLeaveId) throws EmpSickLeaveDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE EMP_SICK_LEAVE_ID = ? ORDER BY EMP_SICK_LEAVE_ID", new Object[] {  new Integer(empSickLeaveId) } );
	}

	/** 
	 * Returns all rows from the EMP_SICK_LEAVE table that match the criteria 'EMPLOYEE_ID = :employeeId'.
	 */
	public EmpSickLeave[] findWhereEmployeeIdEquals(int employeeId) throws EmpSickLeaveDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE EMPLOYEE_ID = ? ORDER BY EMPLOYEE_ID", new Object[] {  new Integer(employeeId) } );
	}

	/** 
	 * Returns all rows from the EMP_SICK_LEAVE table that match the criteria 'DISEASE_ID = :diseaseId'.
	 */
	public EmpSickLeave[] findWhereDiseaseIdEquals(int diseaseId) throws EmpSickLeaveDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE DISEASE_ID = ? ORDER BY DISEASE_ID", new Object[] {  new Integer(diseaseId) } );
	}

	/** 
	 * Returns all rows from the EMP_SICK_LEAVE table that match the criteria 'HOSPITAL_ID = :hospitalId'.
	 */
	public EmpSickLeave[] findWhereHospitalIdEquals(int hospitalId) throws EmpSickLeaveDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE HOSPITAL_ID = ? ORDER BY HOSPITAL_ID", new Object[] {  new Integer(hospitalId) } );
	}

	/** 
	 * Returns all rows from the EMP_SICK_LEAVE table that match the criteria 'EMP_VACATION_ID = :empVacationId'.
	 */
	public EmpSickLeave[] findWhereEmpVacationIdEquals(long empVacationId) throws EmpSickLeaveDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE EMP_VACATION_ID = ? ORDER BY EMP_VACATION_ID", new Object[] {  new Long(empVacationId) } );
	}

	/** 
	 * Returns all rows from the EMP_SICK_LEAVE table that match the criteria 'HOSPITAL_REPORT_IMAGE = :hospitalReportImage'.
	 */
	public EmpSickLeave[] findWhereHospitalReportImageEquals(byte[] hospitalReportImage) throws EmpSickLeaveDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE HOSPITAL_REPORT_IMAGE = ? ORDER BY HOSPITAL_REPORT_IMAGE", new Object[] { hospitalReportImage } );
	}

	/**
	 * Method 'EmpSickLeaveDaoImpl'
	 * 
	 */
	public EmpSickLeaveDaoImpl()
	{
	}

	/**
	 * Method 'EmpSickLeaveDaoImpl'
	 * 
	 * @param userConn
	 */
	public EmpSickLeaveDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "HRMS.EMP_SICK_LEAVE";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected EmpSickLeave fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			EmpSickLeave dto = new EmpSickLeave();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected EmpSickLeave[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			EmpSickLeave dto = new EmpSickLeave();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		EmpSickLeave ret[] = new EmpSickLeave[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(EmpSickLeave dto, ResultSet rs) throws SQLException
	{
		dto.setEmpSickLeaveId( rs.getInt( COLUMN_EMP_SICK_LEAVE_ID ) );
		dto.setEmployeeId( rs.getInt( COLUMN_EMPLOYEE_ID ) );
		dto.setDiseaseId( rs.getInt( COLUMN_DISEASE_ID ) );
		dto.setHospitalId( rs.getInt( COLUMN_HOSPITAL_ID ) );
		dto.setEmpVacationId( rs.getLong( COLUMN_EMP_VACATION_ID ) );
		dto.setHospitalReportImage( super.getBlobColumn(rs, COLUMN_HOSPITAL_REPORT_IMAGE ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(EmpSickLeave dto)
	{
	}

	/** 
	 * Returns all rows from the EMP_SICK_LEAVE table that match the specified arbitrary SQL statement
	 */
	public EmpSickLeave[] findByDynamicSelect(String sql, Object[] sqlParams) throws EmpSickLeaveDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EmpSickLeaveDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the EMP_SICK_LEAVE table that match the specified arbitrary SQL statement
	 */
	public EmpSickLeave[] findByDynamicWhere(String sql, Object[] sqlParams) throws EmpSickLeaveDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EmpSickLeaveDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
