/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.jdbc;

import senior.hrms.emps.dao.*;
import senior.hrms.emps.factory.*;
import senior.hrms.emps.dto.*;
import senior.hrms.emps.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class EndServiceCauseDaoImpl extends AbstractDAO implements EndServiceCauseDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT END_SERVICE_CAUSE_ID, END_SERVICE_CAUSE FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( END_SERVICE_CAUSE_ID, END_SERVICE_CAUSE ) VALUES ( ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET END_SERVICE_CAUSE_ID = ?, END_SERVICE_CAUSE = ? WHERE END_SERVICE_CAUSE_ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE END_SERVICE_CAUSE_ID = ?";

	/** 
	 * Index of column END_SERVICE_CAUSE_ID
	 */
	protected static final int COLUMN_END_SERVICE_CAUSE_ID = 1;

	/** 
	 * Index of column END_SERVICE_CAUSE
	 */
	protected static final int COLUMN_END_SERVICE_CAUSE = 2;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 2;

	/** 
	 * Index of primary-key column END_SERVICE_CAUSE_ID
	 */
	protected static final int PK_COLUMN_END_SERVICE_CAUSE_ID = 1;

	/** 
	 * Inserts a new row in the END_SERVICE_CAUSE table.
	 */
	public EndServiceCausePk insert(EndServiceCause dto) throws EndServiceCauseDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setInt( index++, dto.getEndServiceCauseId() );
			stmt.setString( index++, dto.getEndServiceCause() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EndServiceCauseDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the END_SERVICE_CAUSE table.
	 */
	public void update(EndServiceCausePk pk, EndServiceCause dto) throws EndServiceCauseDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getEndServiceCauseId() );
			stmt.setString( index++, dto.getEndServiceCause() );
			stmt.setInt( 3, pk.getEndServiceCauseId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EndServiceCauseDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the END_SERVICE_CAUSE table.
	 */
	public void delete(EndServiceCausePk pk) throws EndServiceCauseDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getEndServiceCauseId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EndServiceCauseDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the END_SERVICE_CAUSE table that matches the specified primary-key value.
	 */
	public EndServiceCause findByPrimaryKey(EndServiceCausePk pk) throws EndServiceCauseDaoException
	{
		return findByPrimaryKey( pk.getEndServiceCauseId() );
	}

	/** 
	 * Returns all rows from the END_SERVICE_CAUSE table that match the criteria 'END_SERVICE_CAUSE_ID = :endServiceCauseId'.
	 */
	public EndServiceCause findByPrimaryKey(int endServiceCauseId) throws EndServiceCauseDaoException
	{
		EndServiceCause ret[] = findByDynamicSelect( SQL_SELECT + " WHERE END_SERVICE_CAUSE_ID = ?", new Object[] {  new Integer(endServiceCauseId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the END_SERVICE_CAUSE table that match the criteria ''.
	 */
	public EndServiceCause[] findAll() throws EndServiceCauseDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY END_SERVICE_CAUSE_ID", null );
	}

	/** 
	 * Returns all rows from the END_SERVICE_CAUSE table that match the criteria 'END_SERVICE_CAUSE_ID = :endServiceCauseId'.
	 */
	public EndServiceCause[] findWhereEndServiceCauseIdEquals(int endServiceCauseId) throws EndServiceCauseDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE END_SERVICE_CAUSE_ID = ? ORDER BY END_SERVICE_CAUSE_ID", new Object[] {  new Integer(endServiceCauseId) } );
	}

	/** 
	 * Returns all rows from the END_SERVICE_CAUSE table that match the criteria 'END_SERVICE_CAUSE = :endServiceCause'.
	 */
	public EndServiceCause[] findWhereEndServiceCauseEquals(String endServiceCause) throws EndServiceCauseDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE END_SERVICE_CAUSE = ? ORDER BY END_SERVICE_CAUSE", new Object[] { endServiceCause } );
	}

	/**
	 * Method 'EndServiceCauseDaoImpl'
	 * 
	 */
	public EndServiceCauseDaoImpl()
	{
	}

	/**
	 * Method 'EndServiceCauseDaoImpl'
	 * 
	 * @param userConn
	 */
	public EndServiceCauseDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "HRMS.END_SERVICE_CAUSE";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected EndServiceCause fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			EndServiceCause dto = new EndServiceCause();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected EndServiceCause[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			EndServiceCause dto = new EndServiceCause();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		EndServiceCause ret[] = new EndServiceCause[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(EndServiceCause dto, ResultSet rs) throws SQLException
	{
		dto.setEndServiceCauseId( rs.getInt( COLUMN_END_SERVICE_CAUSE_ID ) );
		dto.setEndServiceCause( rs.getString( COLUMN_END_SERVICE_CAUSE ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(EndServiceCause dto)
	{
	}

	/** 
	 * Returns all rows from the END_SERVICE_CAUSE table that match the specified arbitrary SQL statement
	 */
	public EndServiceCause[] findByDynamicSelect(String sql, Object[] sqlParams) throws EndServiceCauseDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EndServiceCauseDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the END_SERVICE_CAUSE table that match the specified arbitrary SQL statement
	 */
	public EndServiceCause[] findByDynamicWhere(String sql, Object[] sqlParams) throws EndServiceCauseDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EndServiceCauseDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
