/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.jdbc;

import senior.hrms.emps.dao.*;
import senior.hrms.emps.factory.*;
import senior.hrms.emps.dto.*;
import senior.hrms.emps.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class HospitalsDaoImpl extends AbstractDAO implements HospitalsDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT HOSPITAL_ID, HOSPITAL_NAME, HOSPITAL_ADDRESS, PHONE_1, PHONE_2, RESPONSIBLE FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( HOSPITAL_ID, HOSPITAL_NAME, HOSPITAL_ADDRESS, PHONE_1, PHONE_2, RESPONSIBLE ) VALUES ( ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET HOSPITAL_ID = ?, HOSPITAL_NAME = ?, HOSPITAL_ADDRESS = ?, PHONE_1 = ?, PHONE_2 = ?, RESPONSIBLE = ? WHERE HOSPITAL_ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE HOSPITAL_ID = ?";

	/** 
	 * Index of column HOSPITAL_ID
	 */
	protected static final int COLUMN_HOSPITAL_ID = 1;

	/** 
	 * Index of column HOSPITAL_NAME
	 */
	protected static final int COLUMN_HOSPITAL_NAME = 2;

	/** 
	 * Index of column HOSPITAL_ADDRESS
	 */
	protected static final int COLUMN_HOSPITAL_ADDRESS = 3;

	/** 
	 * Index of column PHONE_1
	 */
	protected static final int COLUMN_PHONE1 = 4;

	/** 
	 * Index of column PHONE_2
	 */
	protected static final int COLUMN_PHONE2 = 5;

	/** 
	 * Index of column RESPONSIBLE
	 */
	protected static final int COLUMN_RESPONSIBLE = 6;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 6;

	/** 
	 * Index of primary-key column HOSPITAL_ID
	 */
	protected static final int PK_COLUMN_HOSPITAL_ID = 1;

	/** 
	 * Inserts a new row in the HOSPITALS table.
	 */
	public HospitalsPk insert(Hospitals dto) throws HospitalsDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setInt( index++, dto.getHospitalId() );
			stmt.setString( index++, dto.getHospitalName() );
			stmt.setString( index++, dto.getHospitalAddress() );
			stmt.setString( index++, dto.getPhone1() );
			stmt.setString( index++, dto.getPhone2() );
			stmt.setString( index++, dto.getResponsible() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new HospitalsDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the HOSPITALS table.
	 */
	public void update(HospitalsPk pk, Hospitals dto) throws HospitalsDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getHospitalId() );
			stmt.setString( index++, dto.getHospitalName() );
			stmt.setString( index++, dto.getHospitalAddress() );
			stmt.setString( index++, dto.getPhone1() );
			stmt.setString( index++, dto.getPhone2() );
			stmt.setString( index++, dto.getResponsible() );
			stmt.setInt( 7, pk.getHospitalId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new HospitalsDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the HOSPITALS table.
	 */
	public void delete(HospitalsPk pk) throws HospitalsDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getHospitalId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new HospitalsDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the HOSPITALS table that matches the specified primary-key value.
	 */
	public Hospitals findByPrimaryKey(HospitalsPk pk) throws HospitalsDaoException
	{
		return findByPrimaryKey( pk.getHospitalId() );
	}

	/** 
	 * Returns all rows from the HOSPITALS table that match the criteria 'HOSPITAL_ID = :hospitalId'.
	 */
	public Hospitals findByPrimaryKey(int hospitalId) throws HospitalsDaoException
	{
		Hospitals ret[] = findByDynamicSelect( SQL_SELECT + " WHERE HOSPITAL_ID = ?", new Object[] {  new Integer(hospitalId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the HOSPITALS table that match the criteria ''.
	 */
	public Hospitals[] findAll() throws HospitalsDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY HOSPITAL_ID", null );
	}

	/** 
	 * Returns all rows from the HOSPITALS table that match the criteria 'HOSPITAL_ID = :hospitalId'.
	 */
	public Hospitals[] findWhereHospitalIdEquals(int hospitalId) throws HospitalsDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE HOSPITAL_ID = ? ORDER BY HOSPITAL_ID", new Object[] {  new Integer(hospitalId) } );
	}

	/** 
	 * Returns all rows from the HOSPITALS table that match the criteria 'HOSPITAL_NAME = :hospitalName'.
	 */
	public Hospitals[] findWhereHospitalNameEquals(String hospitalName) throws HospitalsDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE HOSPITAL_NAME = ? ORDER BY HOSPITAL_NAME", new Object[] { hospitalName } );
	}

	/** 
	 * Returns all rows from the HOSPITALS table that match the criteria 'HOSPITAL_ADDRESS = :hospitalAddress'.
	 */
	public Hospitals[] findWhereHospitalAddressEquals(String hospitalAddress) throws HospitalsDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE HOSPITAL_ADDRESS = ? ORDER BY HOSPITAL_ADDRESS", new Object[] { hospitalAddress } );
	}

	/** 
	 * Returns all rows from the HOSPITALS table that match the criteria 'PHONE_1 = :phone1'.
	 */
	public Hospitals[] findWherePhone1Equals(String phone1) throws HospitalsDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PHONE_1 = ? ORDER BY PHONE_1", new Object[] { phone1 } );
	}

	/** 
	 * Returns all rows from the HOSPITALS table that match the criteria 'PHONE_2 = :phone2'.
	 */
	public Hospitals[] findWherePhone2Equals(String phone2) throws HospitalsDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PHONE_2 = ? ORDER BY PHONE_2", new Object[] { phone2 } );
	}

	/** 
	 * Returns all rows from the HOSPITALS table that match the criteria 'RESPONSIBLE = :responsible'.
	 */
	public Hospitals[] findWhereResponsibleEquals(String responsible) throws HospitalsDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE RESPONSIBLE = ? ORDER BY RESPONSIBLE", new Object[] { responsible } );
	}

	/**
	 * Method 'HospitalsDaoImpl'
	 * 
	 */
	public HospitalsDaoImpl()
	{
	}

	/**
	 * Method 'HospitalsDaoImpl'
	 * 
	 * @param userConn
	 */
	public HospitalsDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "HRMS.HOSPITALS";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Hospitals fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Hospitals dto = new Hospitals();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Hospitals[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Hospitals dto = new Hospitals();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Hospitals ret[] = new Hospitals[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Hospitals dto, ResultSet rs) throws SQLException
	{
		dto.setHospitalId( rs.getInt( COLUMN_HOSPITAL_ID ) );
		dto.setHospitalName( rs.getString( COLUMN_HOSPITAL_NAME ) );
		dto.setHospitalAddress( rs.getString( COLUMN_HOSPITAL_ADDRESS ) );
		dto.setPhone1( rs.getString( COLUMN_PHONE1 ) );
		dto.setPhone2( rs.getString( COLUMN_PHONE2 ) );
		dto.setResponsible( rs.getString( COLUMN_RESPONSIBLE ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Hospitals dto)
	{
	}

	/** 
	 * Returns all rows from the HOSPITALS table that match the specified arbitrary SQL statement
	 */
	public Hospitals[] findByDynamicSelect(String sql, Object[] sqlParams) throws HospitalsDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new HospitalsDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the HOSPITALS table that match the specified arbitrary SQL statement
	 */
	public Hospitals[] findByDynamicWhere(String sql, Object[] sqlParams) throws HospitalsDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new HospitalsDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
