/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.jdbc;

import senior.hrms.emps.dao.*;
import senior.hrms.emps.factory.*;
import senior.hrms.emps.dto.*;
import senior.hrms.emps.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class LeavesDaoImpl extends AbstractDAO implements LeavesDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT LEAVE_ID, LEAVE_NAME FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( LEAVE_ID, LEAVE_NAME ) VALUES ( ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET LEAVE_ID = ?, LEAVE_NAME = ? WHERE LEAVE_ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE LEAVE_ID = ?";

	/** 
	 * Index of column LEAVE_ID
	 */
	protected static final int COLUMN_LEAVE_ID = 1;

	/** 
	 * Index of column LEAVE_NAME
	 */
	protected static final int COLUMN_LEAVE_NAME = 2;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 2;

	/** 
	 * Index of primary-key column LEAVE_ID
	 */
	protected static final int PK_COLUMN_LEAVE_ID = 1;

	/** 
	 * Inserts a new row in the LEAVES table.
	 */
	public LeavesPk insert(Leaves dto) throws LeavesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setInt( index++, dto.getLeaveId() );
			stmt.setString( index++, dto.getLeaveName() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new LeavesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the LEAVES table.
	 */
	public void update(LeavesPk pk, Leaves dto) throws LeavesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getLeaveId() );
			stmt.setString( index++, dto.getLeaveName() );
			stmt.setInt( 3, pk.getLeaveId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new LeavesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the LEAVES table.
	 */
	public void delete(LeavesPk pk) throws LeavesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getLeaveId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new LeavesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the LEAVES table that matches the specified primary-key value.
	 */
	public Leaves findByPrimaryKey(LeavesPk pk) throws LeavesDaoException
	{
		return findByPrimaryKey( pk.getLeaveId() );
	}

	/** 
	 * Returns all rows from the LEAVES table that match the criteria 'LEAVE_ID = :leaveId'.
	 */
	public Leaves findByPrimaryKey(int leaveId) throws LeavesDaoException
	{
		Leaves ret[] = findByDynamicSelect( SQL_SELECT + " WHERE LEAVE_ID = ?", new Object[] {  new Integer(leaveId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the LEAVES table that match the criteria ''.
	 */
	public Leaves[] findAll() throws LeavesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY LEAVE_ID", null );
	}

	/** 
	 * Returns all rows from the LEAVES table that match the criteria 'LEAVE_ID = :leaveId'.
	 */
	public Leaves[] findWhereLeaveIdEquals(int leaveId) throws LeavesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE LEAVE_ID = ? ORDER BY LEAVE_ID", new Object[] {  new Integer(leaveId) } );
	}

	/** 
	 * Returns all rows from the LEAVES table that match the criteria 'LEAVE_NAME = :leaveName'.
	 */
	public Leaves[] findWhereLeaveNameEquals(String leaveName) throws LeavesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE LEAVE_NAME = ? ORDER BY LEAVE_NAME", new Object[] { leaveName } );
	}

	/**
	 * Method 'LeavesDaoImpl'
	 * 
	 */
	public LeavesDaoImpl()
	{
	}

	/**
	 * Method 'LeavesDaoImpl'
	 * 
	 * @param userConn
	 */
	public LeavesDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "HRMS.LEAVES";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Leaves fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Leaves dto = new Leaves();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Leaves[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Leaves dto = new Leaves();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Leaves ret[] = new Leaves[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Leaves dto, ResultSet rs) throws SQLException
	{
		dto.setLeaveId( rs.getInt( COLUMN_LEAVE_ID ) );
		dto.setLeaveName( rs.getString( COLUMN_LEAVE_NAME ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Leaves dto)
	{
	}

	/** 
	 * Returns all rows from the LEAVES table that match the specified arbitrary SQL statement
	 */
	public Leaves[] findByDynamicSelect(String sql, Object[] sqlParams) throws LeavesDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new LeavesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the LEAVES table that match the specified arbitrary SQL statement
	 */
	public Leaves[] findByDynamicWhere(String sql, Object[] sqlParams) throws LeavesDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new LeavesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
