/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dto;

import senior.hrms.emps.dao.*;
import senior.hrms.emps.factory.*;
import senior.hrms.emps.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class AccidentTypes implements Serializable
{
	/** 
	 * This attribute maps to the column ACCIDENT_TYPE_ID in the ACCIDENT_TYPES table.
	 */
	protected int accidentTypeId;

	/** 
	 * This attribute maps to the column ACCIDENT_TYPE in the ACCIDENT_TYPES table.
	 */
	protected String accidentType;

	/**
	 * Method 'AccidentTypes'
	 * 
	 */
	public AccidentTypes()
	{
	}

	/**
	 * Method 'getAccidentTypeId'
	 * 
	 * @return int
	 */
	public int getAccidentTypeId()
	{
		return accidentTypeId;
	}

	/**
	 * Method 'setAccidentTypeId'
	 * 
	 * @param accidentTypeId
	 */
	public void setAccidentTypeId(int accidentTypeId)
	{
		this.accidentTypeId = accidentTypeId;
	}

	/**
	 * Method 'getAccidentType'
	 * 
	 * @return String
	 */
	public String getAccidentType()
	{
		return accidentType;
	}

	/**
	 * Method 'setAccidentType'
	 * 
	 * @param accidentType
	 */
	public void setAccidentType(String accidentType)
	{
		this.accidentType = accidentType;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof AccidentTypes)) {
			return false;
		}
		
		final AccidentTypes _cast = (AccidentTypes) _other;
		if (accidentTypeId != _cast.accidentTypeId) {
			return false;
		}
		
		if (accidentType == null ? _cast.accidentType != accidentType : !accidentType.equals( _cast.accidentType )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + accidentTypeId;
		if (accidentType != null) {
			_hashCode = 29 * _hashCode + accidentType.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return AccidentTypesPk
	 */
	public AccidentTypesPk createPk()
	{
		return new AccidentTypesPk(accidentTypeId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "senior.hrms.emps.dto.AccidentTypes: " );
		ret.append( "accidentTypeId=" + accidentTypeId );
		ret.append( ", accidentType=" + accidentType );
		return ret.toString();
	}

}
