/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the BLOOD_CATEGORIES table.
 */
public class BloodCategoriesPk implements Serializable
{
	protected int bloodCategoryId;

	/** 
	 * This attribute represents whether the primitive attribute bloodCategoryId is null.
	 */
	protected boolean bloodCategoryIdNull;

	/** 
	 * Sets the value of bloodCategoryId
	 */
	public void setBloodCategoryId(int bloodCategoryId)
	{
		this.bloodCategoryId = bloodCategoryId;
	}

	/** 
	 * Gets the value of bloodCategoryId
	 */
	public int getBloodCategoryId()
	{
		return bloodCategoryId;
	}

	/**
	 * Method 'BloodCategoriesPk'
	 * 
	 */
	public BloodCategoriesPk()
	{
	}

	/**
	 * Method 'BloodCategoriesPk'
	 * 
	 * @param bloodCategoryId
	 */
	public BloodCategoriesPk(final int bloodCategoryId)
	{
		this.bloodCategoryId = bloodCategoryId;
	}

	/** 
	 * Sets the value of bloodCategoryIdNull
	 */
	public void setBloodCategoryIdNull(boolean bloodCategoryIdNull)
	{
		this.bloodCategoryIdNull = bloodCategoryIdNull;
	}

	/** 
	 * Gets the value of bloodCategoryIdNull
	 */
	public boolean isBloodCategoryIdNull()
	{
		return bloodCategoryIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof BloodCategoriesPk)) {
			return false;
		}
		
		final BloodCategoriesPk _cast = (BloodCategoriesPk) _other;
		if (bloodCategoryId != _cast.bloodCategoryId) {
			return false;
		}
		
		if (bloodCategoryIdNull != _cast.bloodCategoryIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + bloodCategoryId;
		_hashCode = 29 * _hashCode + (bloodCategoryIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "senior.hrms.emps.dto.BloodCategoriesPk: " );
		ret.append( "bloodCategoryId=" + bloodCategoryId );
		return ret.toString();
	}

}
