/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the CAR_LICENCE_TYPE table.
 */
public class CarLicenceTypePk implements Serializable
{
	protected int carLicenceTypeId;

	/** 
	 * This attribute represents whether the primitive attribute carLicenceTypeId is null.
	 */
	protected boolean carLicenceTypeIdNull;

	/** 
	 * Sets the value of carLicenceTypeId
	 */
	public void setCarLicenceTypeId(int carLicenceTypeId)
	{
		this.carLicenceTypeId = carLicenceTypeId;
	}

	/** 
	 * Gets the value of carLicenceTypeId
	 */
	public int getCarLicenceTypeId()
	{
		return carLicenceTypeId;
	}

	/**
	 * Method 'CarLicenceTypePk'
	 * 
	 */
	public CarLicenceTypePk()
	{
	}

	/**
	 * Method 'CarLicenceTypePk'
	 * 
	 * @param carLicenceTypeId
	 */
	public CarLicenceTypePk(final int carLicenceTypeId)
	{
		this.carLicenceTypeId = carLicenceTypeId;
	}

	/** 
	 * Sets the value of carLicenceTypeIdNull
	 */
	public void setCarLicenceTypeIdNull(boolean carLicenceTypeIdNull)
	{
		this.carLicenceTypeIdNull = carLicenceTypeIdNull;
	}

	/** 
	 * Gets the value of carLicenceTypeIdNull
	 */
	public boolean isCarLicenceTypeIdNull()
	{
		return carLicenceTypeIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CarLicenceTypePk)) {
			return false;
		}
		
		final CarLicenceTypePk _cast = (CarLicenceTypePk) _other;
		if (carLicenceTypeId != _cast.carLicenceTypeId) {
			return false;
		}
		
		if (carLicenceTypeIdNull != _cast.carLicenceTypeIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + carLicenceTypeId;
		_hashCode = 29 * _hashCode + (carLicenceTypeIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "senior.hrms.emps.dto.CarLicenceTypePk: " );
		ret.append( "carLicenceTypeId=" + carLicenceTypeId );
		return ret.toString();
	}

}
