/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dto;

import senior.hrms.emps.dao.*;
import senior.hrms.emps.factory.*;
import senior.hrms.emps.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Degree implements Serializable
{
	/** 
	 * This attribute maps to the column DEGREE_ID in the DEGREE table.
	 */
	protected int degreeId;

	/** 
	 * This attribute maps to the column DEGEREE_NAME in the DEGREE table.
	 */
	protected String degereeName;

	/**
	 * Method 'Degree'
	 * 
	 */
	public Degree()
	{
	}

	/**
	 * Method 'getDegreeId'
	 * 
	 * @return int
	 */
	public int getDegreeId()
	{
		return degreeId;
	}

	/**
	 * Method 'setDegreeId'
	 * 
	 * @param degreeId
	 */
	public void setDegreeId(int degreeId)
	{
		this.degreeId = degreeId;
	}

	/**
	 * Method 'getDegereeName'
	 * 
	 * @return String
	 */
	public String getDegereeName()
	{
		return degereeName;
	}

	/**
	 * Method 'setDegereeName'
	 * 
	 * @param degereeName
	 */
	public void setDegereeName(String degereeName)
	{
		this.degereeName = degereeName;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Degree)) {
			return false;
		}
		
		final Degree _cast = (Degree) _other;
		if (degreeId != _cast.degreeId) {
			return false;
		}
		
		if (degereeName == null ? _cast.degereeName != degereeName : !degereeName.equals( _cast.degereeName )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + degreeId;
		if (degereeName != null) {
			_hashCode = 29 * _hashCode + degereeName.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return DegreePk
	 */
	public DegreePk createPk()
	{
		return new DegreePk(degreeId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "senior.hrms.emps.dto.Degree: " );
		ret.append( "degreeId=" + degreeId );
		ret.append( ", degereeName=" + degereeName );
		return ret.toString();
	}

}
