/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the DISEASES table.
 */
public class DiseasesPk implements Serializable
{
	protected int diseaseId;

	/** 
	 * This attribute represents whether the primitive attribute diseaseId is null.
	 */
	protected boolean diseaseIdNull;

	/** 
	 * Sets the value of diseaseId
	 */
	public void setDiseaseId(int diseaseId)
	{
		this.diseaseId = diseaseId;
	}

	/** 
	 * Gets the value of diseaseId
	 */
	public int getDiseaseId()
	{
		return diseaseId;
	}

	/**
	 * Method 'DiseasesPk'
	 * 
	 */
	public DiseasesPk()
	{
	}

	/**
	 * Method 'DiseasesPk'
	 * 
	 * @param diseaseId
	 */
	public DiseasesPk(final int diseaseId)
	{
		this.diseaseId = diseaseId;
	}

	/** 
	 * Sets the value of diseaseIdNull
	 */
	public void setDiseaseIdNull(boolean diseaseIdNull)
	{
		this.diseaseIdNull = diseaseIdNull;
	}

	/** 
	 * Gets the value of diseaseIdNull
	 */
	public boolean isDiseaseIdNull()
	{
		return diseaseIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DiseasesPk)) {
			return false;
		}
		
		final DiseasesPk _cast = (DiseasesPk) _other;
		if (diseaseId != _cast.diseaseId) {
			return false;
		}
		
		if (diseaseIdNull != _cast.diseaseIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + diseaseId;
		_hashCode = 29 * _hashCode + (diseaseIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "senior.hrms.emps.dto.DiseasesPk: " );
		ret.append( "diseaseId=" + diseaseId );
		return ret.toString();
	}

}
