/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dto;

import senior.hrms.emps.dao.*;
import senior.hrms.emps.factory.*;
import senior.hrms.emps.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class EmpCourses implements Serializable
{
	/** 
	 * This attribute maps to the column EMP_COURSE_ID in the EMP_COURSES table.
	 */
	protected int empCourseId;

	/** 
	 * This attribute maps to the column EMPLOYEE_ID in the EMP_COURSES table.
	 */
	protected int employeeId;

	/** 
	 * This attribute maps to the column COURSE_ID in the EMP_COURSES table.
	 */
	protected int courseId;

	/**
	 * Method 'EmpCourses'
	 * 
	 */
	public EmpCourses()
	{
	}

	/**
	 * Method 'getEmpCourseId'
	 * 
	 * @return int
	 */
	public int getEmpCourseId()
	{
		return empCourseId;
	}

	/**
	 * Method 'setEmpCourseId'
	 * 
	 * @param empCourseId
	 */
	public void setEmpCourseId(int empCourseId)
	{
		this.empCourseId = empCourseId;
	}

	/**
	 * Method 'getEmployeeId'
	 * 
	 * @return int
	 */
	public int getEmployeeId()
	{
		return employeeId;
	}

	/**
	 * Method 'setEmployeeId'
	 * 
	 * @param employeeId
	 */
	public void setEmployeeId(int employeeId)
	{
		this.employeeId = employeeId;
	}

	/**
	 * Method 'getCourseId'
	 * 
	 * @return int
	 */
	public int getCourseId()
	{
		return courseId;
	}

	/**
	 * Method 'setCourseId'
	 * 
	 * @param courseId
	 */
	public void setCourseId(int courseId)
	{
		this.courseId = courseId;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof EmpCourses)) {
			return false;
		}
		
		final EmpCourses _cast = (EmpCourses) _other;
		if (empCourseId != _cast.empCourseId) {
			return false;
		}
		
		if (employeeId != _cast.employeeId) {
			return false;
		}
		
		if (courseId != _cast.courseId) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + empCourseId;
		_hashCode = 29 * _hashCode + employeeId;
		_hashCode = 29 * _hashCode + courseId;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return EmpCoursesPk
	 */
	public EmpCoursesPk createPk()
	{
		return new EmpCoursesPk(empCourseId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "senior.hrms.emps.dto.EmpCourses: " );
		ret.append( "empCourseId=" + empCourseId );
		ret.append( ", employeeId=" + employeeId );
		ret.append( ", courseId=" + courseId );
		return ret.toString();
	}

}
