/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the EVALUATION_ITEM table.
 */
public class EvaluationItemPk implements Serializable
{
	protected int evaluationItemId;

	/** 
	 * This attribute represents whether the primitive attribute evaluationItemId is null.
	 */
	protected boolean evaluationItemIdNull;

	/** 
	 * Sets the value of evaluationItemId
	 */
	public void setEvaluationItemId(int evaluationItemId)
	{
		this.evaluationItemId = evaluationItemId;
	}

	/** 
	 * Gets the value of evaluationItemId
	 */
	public int getEvaluationItemId()
	{
		return evaluationItemId;
	}

	/**
	 * Method 'EvaluationItemPk'
	 * 
	 */
	public EvaluationItemPk()
	{
	}

	/**
	 * Method 'EvaluationItemPk'
	 * 
	 * @param evaluationItemId
	 */
	public EvaluationItemPk(final int evaluationItemId)
	{
		this.evaluationItemId = evaluationItemId;
	}

	/** 
	 * Sets the value of evaluationItemIdNull
	 */
	public void setEvaluationItemIdNull(boolean evaluationItemIdNull)
	{
		this.evaluationItemIdNull = evaluationItemIdNull;
	}

	/** 
	 * Gets the value of evaluationItemIdNull
	 */
	public boolean isEvaluationItemIdNull()
	{
		return evaluationItemIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof EvaluationItemPk)) {
			return false;
		}
		
		final EvaluationItemPk _cast = (EvaluationItemPk) _other;
		if (evaluationItemId != _cast.evaluationItemId) {
			return false;
		}
		
		if (evaluationItemIdNull != _cast.evaluationItemIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + evaluationItemId;
		_hashCode = 29 * _hashCode + (evaluationItemIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "senior.hrms.emps.dto.EvaluationItemPk: " );
		ret.append( "evaluationItemId=" + evaluationItemId );
		return ret.toString();
	}

}
