/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the GRADE table.
 */
public class GradePk implements Serializable
{
	protected int gradeId;

	/** 
	 * This attribute represents whether the primitive attribute gradeId is null.
	 */
	protected boolean gradeIdNull;

	/** 
	 * Sets the value of gradeId
	 */
	public void setGradeId(int gradeId)
	{
		this.gradeId = gradeId;
	}

	/** 
	 * Gets the value of gradeId
	 */
	public int getGradeId()
	{
		return gradeId;
	}

	/**
	 * Method 'GradePk'
	 * 
	 */
	public GradePk()
	{
	}

	/**
	 * Method 'GradePk'
	 * 
	 * @param gradeId
	 */
	public GradePk(final int gradeId)
	{
		this.gradeId = gradeId;
	}

	/** 
	 * Sets the value of gradeIdNull
	 */
	public void setGradeIdNull(boolean gradeIdNull)
	{
		this.gradeIdNull = gradeIdNull;
	}

	/** 
	 * Gets the value of gradeIdNull
	 */
	public boolean isGradeIdNull()
	{
		return gradeIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof GradePk)) {
			return false;
		}
		
		final GradePk _cast = (GradePk) _other;
		if (gradeId != _cast.gradeId) {
			return false;
		}
		
		if (gradeIdNull != _cast.gradeIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + gradeId;
		_hashCode = 29 * _hashCode + (gradeIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "senior.hrms.emps.dto.GradePk: " );
		ret.append( "gradeId=" + gradeId );
		return ret.toString();
	}

}
