/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dto;

import senior.hrms.emps.dao.*;
import senior.hrms.emps.factory.*;
import senior.hrms.emps.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Institutions implements Serializable
{
	/** 
	 * This attribute maps to the column INSTITUTE_ID in the INSTITUTIONS table.
	 */
	protected int instituteId;

	/** 
	 * This attribute maps to the column INSTITUTE_NAME in the INSTITUTIONS table.
	 */
	protected String instituteName;

	/** 
	 * This attribute maps to the column INSTITUTE_CITY_ID in the INSTITUTIONS table.
	 */
	protected int instituteCityId;

	/** 
	 * This attribute represents whether the primitive attribute instituteCityId is null.
	 */
	protected boolean instituteCityIdNull = true;

	/** 
	 * This attribute maps to the column INSTITUTE_ADDRESS in the INSTITUTIONS table.
	 */
	protected String instituteAddress;

	/** 
	 * This attribute maps to the column INSTITUTE_WEB_SITE in the INSTITUTIONS table.
	 */
	protected String instituteWebSite;

	/**
	 * Method 'Institutions'
	 * 
	 */
	public Institutions()
	{
	}

	/**
	 * Method 'getInstituteId'
	 * 
	 * @return int
	 */
	public int getInstituteId()
	{
		return instituteId;
	}

	/**
	 * Method 'setInstituteId'
	 * 
	 * @param instituteId
	 */
	public void setInstituteId(int instituteId)
	{
		this.instituteId = instituteId;
	}

	/**
	 * Method 'getInstituteName'
	 * 
	 * @return String
	 */
	public String getInstituteName()
	{
		return instituteName;
	}

	/**
	 * Method 'setInstituteName'
	 * 
	 * @param instituteName
	 */
	public void setInstituteName(String instituteName)
	{
		this.instituteName = instituteName;
	}

	/**
	 * Method 'getInstituteCityId'
	 * 
	 * @return int
	 */
	public int getInstituteCityId()
	{
		return instituteCityId;
	}

	/**
	 * Method 'setInstituteCityId'
	 * 
	 * @param instituteCityId
	 */
	public void setInstituteCityId(int instituteCityId)
	{
		this.instituteCityId = instituteCityId;
		this.instituteCityIdNull = false;
	}

	/**
	 * Method 'setInstituteCityIdNull'
	 * 
	 * @param value
	 */
	public void setInstituteCityIdNull(boolean value)
	{
		this.instituteCityIdNull = value;
	}

	/**
	 * Method 'isInstituteCityIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isInstituteCityIdNull()
	{
		return instituteCityIdNull;
	}

	/**
	 * Method 'getInstituteAddress'
	 * 
	 * @return String
	 */
	public String getInstituteAddress()
	{
		return instituteAddress;
	}

	/**
	 * Method 'setInstituteAddress'
	 * 
	 * @param instituteAddress
	 */
	public void setInstituteAddress(String instituteAddress)
	{
		this.instituteAddress = instituteAddress;
	}

	/**
	 * Method 'getInstituteWebSite'
	 * 
	 * @return String
	 */
	public String getInstituteWebSite()
	{
		return instituteWebSite;
	}

	/**
	 * Method 'setInstituteWebSite'
	 * 
	 * @param instituteWebSite
	 */
	public void setInstituteWebSite(String instituteWebSite)
	{
		this.instituteWebSite = instituteWebSite;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Institutions)) {
			return false;
		}
		
		final Institutions _cast = (Institutions) _other;
		if (instituteId != _cast.instituteId) {
			return false;
		}
		
		if (instituteName == null ? _cast.instituteName != instituteName : !instituteName.equals( _cast.instituteName )) {
			return false;
		}
		
		if (instituteCityId != _cast.instituteCityId) {
			return false;
		}
		
		if (instituteCityIdNull != _cast.instituteCityIdNull) {
			return false;
		}
		
		if (instituteAddress == null ? _cast.instituteAddress != instituteAddress : !instituteAddress.equals( _cast.instituteAddress )) {
			return false;
		}
		
		if (instituteWebSite == null ? _cast.instituteWebSite != instituteWebSite : !instituteWebSite.equals( _cast.instituteWebSite )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + instituteId;
		if (instituteName != null) {
			_hashCode = 29 * _hashCode + instituteName.hashCode();
		}
		
		_hashCode = 29 * _hashCode + instituteCityId;
		_hashCode = 29 * _hashCode + (instituteCityIdNull ? 1 : 0);
		if (instituteAddress != null) {
			_hashCode = 29 * _hashCode + instituteAddress.hashCode();
		}
		
		if (instituteWebSite != null) {
			_hashCode = 29 * _hashCode + instituteWebSite.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return InstitutionsPk
	 */
	public InstitutionsPk createPk()
	{
		return new InstitutionsPk(instituteId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "senior.hrms.emps.dto.Institutions: " );
		ret.append( "instituteId=" + instituteId );
		ret.append( ", instituteName=" + instituteName );
		ret.append( ", instituteCityId=" + instituteCityId );
		ret.append( ", instituteAddress=" + instituteAddress );
		ret.append( ", instituteWebSite=" + instituteWebSite );
		return ret.toString();
	}

}
