/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dto;

import senior.hrms.emps.dao.*;
import senior.hrms.emps.factory.*;
import senior.hrms.emps.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class JobLevel implements Serializable
{
	/** 
	 * This attribute maps to the column JOB_LEVEL_ID in the JOB_LEVEL table.
	 */
	protected int jobLevelId;

	/** 
	 * This attribute maps to the column JOB_LEVEL_NAME in the JOB_LEVEL table.
	 */
	protected String jobLevelName;

	/**
	 * Method 'JobLevel'
	 * 
	 */
	public JobLevel()
	{
	}

	/**
	 * Method 'getJobLevelId'
	 * 
	 * @return int
	 */
	public int getJobLevelId()
	{
		return jobLevelId;
	}

	/**
	 * Method 'setJobLevelId'
	 * 
	 * @param jobLevelId
	 */
	public void setJobLevelId(int jobLevelId)
	{
		this.jobLevelId = jobLevelId;
	}

	/**
	 * Method 'getJobLevelName'
	 * 
	 * @return String
	 */
	public String getJobLevelName()
	{
		return jobLevelName;
	}

	/**
	 * Method 'setJobLevelName'
	 * 
	 * @param jobLevelName
	 */
	public void setJobLevelName(String jobLevelName)
	{
		this.jobLevelName = jobLevelName;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof JobLevel)) {
			return false;
		}
		
		final JobLevel _cast = (JobLevel) _other;
		if (jobLevelId != _cast.jobLevelId) {
			return false;
		}
		
		if (jobLevelName == null ? _cast.jobLevelName != jobLevelName : !jobLevelName.equals( _cast.jobLevelName )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + jobLevelId;
		if (jobLevelName != null) {
			_hashCode = 29 * _hashCode + jobLevelName.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return JobLevelPk
	 */
	public JobLevelPk createPk()
	{
		return new JobLevelPk(jobLevelId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "senior.hrms.emps.dto.JobLevel: " );
		ret.append( "jobLevelId=" + jobLevelId );
		ret.append( ", jobLevelName=" + jobLevelName );
		return ret.toString();
	}

}
