/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the MAJOR table.
 */
public class MajorPk implements Serializable
{
	protected int majorId;

	/** 
	 * This attribute represents whether the primitive attribute majorId is null.
	 */
	protected boolean majorIdNull;

	/** 
	 * Sets the value of majorId
	 */
	public void setMajorId(int majorId)
	{
		this.majorId = majorId;
	}

	/** 
	 * Gets the value of majorId
	 */
	public int getMajorId()
	{
		return majorId;
	}

	/**
	 * Method 'MajorPk'
	 * 
	 */
	public MajorPk()
	{
	}

	/**
	 * Method 'MajorPk'
	 * 
	 * @param majorId
	 */
	public MajorPk(final int majorId)
	{
		this.majorId = majorId;
	}

	/** 
	 * Sets the value of majorIdNull
	 */
	public void setMajorIdNull(boolean majorIdNull)
	{
		this.majorIdNull = majorIdNull;
	}

	/** 
	 * Gets the value of majorIdNull
	 */
	public boolean isMajorIdNull()
	{
		return majorIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof MajorPk)) {
			return false;
		}
		
		final MajorPk _cast = (MajorPk) _other;
		if (majorId != _cast.majorId) {
			return false;
		}
		
		if (majorIdNull != _cast.majorIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + majorId;
		_hashCode = 29 * _hashCode + (majorIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "senior.hrms.emps.dto.MajorPk: " );
		ret.append( "majorId=" + majorId );
		return ret.toString();
	}

}
