/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the MILITARY_STATUS table.
 */
public class MilitaryStatusPk implements Serializable
{
	protected int militaryStatusId;

	/** 
	 * This attribute represents whether the primitive attribute militaryStatusId is null.
	 */
	protected boolean militaryStatusIdNull;

	/** 
	 * Sets the value of militaryStatusId
	 */
	public void setMilitaryStatusId(int militaryStatusId)
	{
		this.militaryStatusId = militaryStatusId;
	}

	/** 
	 * Gets the value of militaryStatusId
	 */
	public int getMilitaryStatusId()
	{
		return militaryStatusId;
	}

	/**
	 * Method 'MilitaryStatusPk'
	 * 
	 */
	public MilitaryStatusPk()
	{
	}

	/**
	 * Method 'MilitaryStatusPk'
	 * 
	 * @param militaryStatusId
	 */
	public MilitaryStatusPk(final int militaryStatusId)
	{
		this.militaryStatusId = militaryStatusId;
	}

	/** 
	 * Sets the value of militaryStatusIdNull
	 */
	public void setMilitaryStatusIdNull(boolean militaryStatusIdNull)
	{
		this.militaryStatusIdNull = militaryStatusIdNull;
	}

	/** 
	 * Gets the value of militaryStatusIdNull
	 */
	public boolean isMilitaryStatusIdNull()
	{
		return militaryStatusIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof MilitaryStatusPk)) {
			return false;
		}
		
		final MilitaryStatusPk _cast = (MilitaryStatusPk) _other;
		if (militaryStatusId != _cast.militaryStatusId) {
			return false;
		}
		
		if (militaryStatusIdNull != _cast.militaryStatusIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + militaryStatusId;
		_hashCode = 29 * _hashCode + (militaryStatusIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "senior.hrms.emps.dto.MilitaryStatusPk: " );
		ret.append( "militaryStatusId=" + militaryStatusId );
		return ret.toString();
	}

}
