/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dto;

import senior.hrms.emps.dao.*;
import senior.hrms.emps.factory.*;
import senior.hrms.emps.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class MilitaryStatus implements Serializable
{
	/** 
	 * This attribute maps to the column MILITARY_STATUS_ID in the MILITARY_STATUS table.
	 */
	protected int militaryStatusId;

	/** 
	 * This attribute maps to the column MILITARY_STATUS_NAME in the MILITARY_STATUS table.
	 */
	protected byte[] militaryStatusName;

	/**
	 * Method 'MilitaryStatus'
	 * 
	 */
	public MilitaryStatus()
	{
	}

	/**
	 * Method 'getMilitaryStatusId'
	 * 
	 * @return int
	 */
	public int getMilitaryStatusId()
	{
		return militaryStatusId;
	}

	/**
	 * Method 'setMilitaryStatusId'
	 * 
	 * @param militaryStatusId
	 */
	public void setMilitaryStatusId(int militaryStatusId)
	{
		this.militaryStatusId = militaryStatusId;
	}

	/**
	 * Method 'getMilitaryStatusName'
	 * 
	 * @return byte[]
	 */
	public byte[] getMilitaryStatusName()
	{
		return militaryStatusName;
	}

	/**
	 * Method 'setMilitaryStatusName'
	 * 
	 * @param militaryStatusName
	 */
	public void setMilitaryStatusName(byte[] militaryStatusName)
	{
		this.militaryStatusName = militaryStatusName;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof MilitaryStatus)) {
			return false;
		}
		
		final MilitaryStatus _cast = (MilitaryStatus) _other;
		if (militaryStatusId != _cast.militaryStatusId) {
			return false;
		}
		
		if (militaryStatusName == null ? _cast.militaryStatusName != militaryStatusName : !militaryStatusName.equals( _cast.militaryStatusName )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + militaryStatusId;
		if (militaryStatusName != null) {
			_hashCode = 29 * _hashCode + militaryStatusName.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return MilitaryStatusPk
	 */
	public MilitaryStatusPk createPk()
	{
		return new MilitaryStatusPk(militaryStatusId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "senior.hrms.emps.dto.MilitaryStatus: " );
		ret.append( "militaryStatusId=" + militaryStatusId );
		ret.append( ", militaryStatusName=" + militaryStatusName );
		return ret.toString();
	}

}
