/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the MISSION_TYPES table.
 */
public class MissionTypesPk implements Serializable
{
	protected int missionTypeId;

	/** 
	 * This attribute represents whether the primitive attribute missionTypeId is null.
	 */
	protected boolean missionTypeIdNull;

	/** 
	 * Sets the value of missionTypeId
	 */
	public void setMissionTypeId(int missionTypeId)
	{
		this.missionTypeId = missionTypeId;
	}

	/** 
	 * Gets the value of missionTypeId
	 */
	public int getMissionTypeId()
	{
		return missionTypeId;
	}

	/**
	 * Method 'MissionTypesPk'
	 * 
	 */
	public MissionTypesPk()
	{
	}

	/**
	 * Method 'MissionTypesPk'
	 * 
	 * @param missionTypeId
	 */
	public MissionTypesPk(final int missionTypeId)
	{
		this.missionTypeId = missionTypeId;
	}

	/** 
	 * Sets the value of missionTypeIdNull
	 */
	public void setMissionTypeIdNull(boolean missionTypeIdNull)
	{
		this.missionTypeIdNull = missionTypeIdNull;
	}

	/** 
	 * Gets the value of missionTypeIdNull
	 */
	public boolean isMissionTypeIdNull()
	{
		return missionTypeIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof MissionTypesPk)) {
			return false;
		}
		
		final MissionTypesPk _cast = (MissionTypesPk) _other;
		if (missionTypeId != _cast.missionTypeId) {
			return false;
		}
		
		if (missionTypeIdNull != _cast.missionTypeIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + missionTypeId;
		_hashCode = 29 * _hashCode + (missionTypeIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "senior.hrms.emps.dto.MissionTypesPk: " );
		ret.append( "missionTypeId=" + missionTypeId );
		return ret.toString();
	}

}
