/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dto;

import senior.hrms.emps.dao.*;
import senior.hrms.emps.factory.*;
import senior.hrms.emps.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class OfficialVacations implements Serializable
{
	/** 
	 * This attribute maps to the column OFFICIAL_VACATION_ID in the OFFICIAL_VACATIONS table.
	 */
	protected int officialVacationId;

	/** 
	 * This attribute maps to the column OFFICIAL_VACATION_NAME in the OFFICIAL_VACATIONS table.
	 */
	protected String officialVacationName;

	/** 
	 * This attribute maps to the column DESCRIPTION in the OFFICIAL_VACATIONS table.
	 */
	protected String description;

	/**
	 * Method 'OfficialVacations'
	 * 
	 */
	public OfficialVacations()
	{
	}

	/**
	 * Method 'getOfficialVacationId'
	 * 
	 * @return int
	 */
	public int getOfficialVacationId()
	{
		return officialVacationId;
	}

	/**
	 * Method 'setOfficialVacationId'
	 * 
	 * @param officialVacationId
	 */
	public void setOfficialVacationId(int officialVacationId)
	{
		this.officialVacationId = officialVacationId;
	}

	/**
	 * Method 'getOfficialVacationName'
	 * 
	 * @return String
	 */
	public String getOfficialVacationName()
	{
		return officialVacationName;
	}

	/**
	 * Method 'setOfficialVacationName'
	 * 
	 * @param officialVacationName
	 */
	public void setOfficialVacationName(String officialVacationName)
	{
		this.officialVacationName = officialVacationName;
	}

	/**
	 * Method 'getDescription'
	 * 
	 * @return String
	 */
	public String getDescription()
	{
		return description;
	}

	/**
	 * Method 'setDescription'
	 * 
	 * @param description
	 */
	public void setDescription(String description)
	{
		this.description = description;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof OfficialVacations)) {
			return false;
		}
		
		final OfficialVacations _cast = (OfficialVacations) _other;
		if (officialVacationId != _cast.officialVacationId) {
			return false;
		}
		
		if (officialVacationName == null ? _cast.officialVacationName != officialVacationName : !officialVacationName.equals( _cast.officialVacationName )) {
			return false;
		}
		
		if (description == null ? _cast.description != description : !description.equals( _cast.description )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + officialVacationId;
		if (officialVacationName != null) {
			_hashCode = 29 * _hashCode + officialVacationName.hashCode();
		}
		
		if (description != null) {
			_hashCode = 29 * _hashCode + description.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return OfficialVacationsPk
	 */
	public OfficialVacationsPk createPk()
	{
		return new OfficialVacationsPk(officialVacationId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "senior.hrms.emps.dto.OfficialVacations: " );
		ret.append( "officialVacationId=" + officialVacationId );
		ret.append( ", officialVacationName=" + officialVacationName );
		ret.append( ", description=" + description );
		return ret.toString();
	}

}
