/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dto;

import senior.hrms.emps.dao.*;
import senior.hrms.emps.factory.*;
import senior.hrms.emps.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class PermitSide implements Serializable
{
	/** 
	 * This attribute maps to the column PERMIT_SIDE_ID in the PERMIT_SIDE table.
	 */
	protected int permitSideId;

	/** 
	 * This attribute maps to the column PERMIT_SIDE_NAME in the PERMIT_SIDE table.
	 */
	protected String permitSideName;

	/**
	 * Method 'PermitSide'
	 * 
	 */
	public PermitSide()
	{
	}

	/**
	 * Method 'getPermitSideId'
	 * 
	 * @return int
	 */
	public int getPermitSideId()
	{
		return permitSideId;
	}

	/**
	 * Method 'setPermitSideId'
	 * 
	 * @param permitSideId
	 */
	public void setPermitSideId(int permitSideId)
	{
		this.permitSideId = permitSideId;
	}

	/**
	 * Method 'getPermitSideName'
	 * 
	 * @return String
	 */
	public String getPermitSideName()
	{
		return permitSideName;
	}

	/**
	 * Method 'setPermitSideName'
	 * 
	 * @param permitSideName
	 */
	public void setPermitSideName(String permitSideName)
	{
		this.permitSideName = permitSideName;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof PermitSide)) {
			return false;
		}
		
		final PermitSide _cast = (PermitSide) _other;
		if (permitSideId != _cast.permitSideId) {
			return false;
		}
		
		if (permitSideName == null ? _cast.permitSideName != permitSideName : !permitSideName.equals( _cast.permitSideName )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + permitSideId;
		if (permitSideName != null) {
			_hashCode = 29 * _hashCode + permitSideName.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return PermitSidePk
	 */
	public PermitSidePk createPk()
	{
		return new PermitSidePk(permitSideId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "senior.hrms.emps.dto.PermitSide: " );
		ret.append( "permitSideId=" + permitSideId );
		ret.append( ", permitSideName=" + permitSideName );
		return ret.toString();
	}

}
