/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dto;

import senior.hrms.emps.dao.*;
import senior.hrms.emps.factory.*;
import senior.hrms.emps.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Projects implements Serializable
{
	/** 
	 * This attribute maps to the column PROJECT_ID in the PROJECTS table.
	 */
	protected int projectId;

	/** 
	 * This attribute maps to the column PROJECT_NAME in the PROJECTS table.
	 */
	protected String projectName;

	/** 
	 * This attribute maps to the column PROJECT_DESCRIPTION in the PROJECTS table.
	 */
	protected String projectDescription;

	/**
	 * Method 'Projects'
	 * 
	 */
	public Projects()
	{
	}

	/**
	 * Method 'getProjectId'
	 * 
	 * @return int
	 */
	public int getProjectId()
	{
		return projectId;
	}

	/**
	 * Method 'setProjectId'
	 * 
	 * @param projectId
	 */
	public void setProjectId(int projectId)
	{
		this.projectId = projectId;
	}

	/**
	 * Method 'getProjectName'
	 * 
	 * @return String
	 */
	public String getProjectName()
	{
		return projectName;
	}

	/**
	 * Method 'setProjectName'
	 * 
	 * @param projectName
	 */
	public void setProjectName(String projectName)
	{
		this.projectName = projectName;
	}

	/**
	 * Method 'getProjectDescription'
	 * 
	 * @return String
	 */
	public String getProjectDescription()
	{
		return projectDescription;
	}

	/**
	 * Method 'setProjectDescription'
	 * 
	 * @param projectDescription
	 */
	public void setProjectDescription(String projectDescription)
	{
		this.projectDescription = projectDescription;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Projects)) {
			return false;
		}
		
		final Projects _cast = (Projects) _other;
		if (projectId != _cast.projectId) {
			return false;
		}
		
		if (projectName == null ? _cast.projectName != projectName : !projectName.equals( _cast.projectName )) {
			return false;
		}
		
		if (projectDescription == null ? _cast.projectDescription != projectDescription : !projectDescription.equals( _cast.projectDescription )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + projectId;
		if (projectName != null) {
			_hashCode = 29 * _hashCode + projectName.hashCode();
		}
		
		if (projectDescription != null) {
			_hashCode = 29 * _hashCode + projectDescription.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ProjectsPk
	 */
	public ProjectsPk createPk()
	{
		return new ProjectsPk(projectId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "senior.hrms.emps.dto.Projects: " );
		ret.append( "projectId=" + projectId );
		ret.append( ", projectName=" + projectName );
		ret.append( ", projectDescription=" + projectDescription );
		return ret.toString();
	}

}
