/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dto;

import senior.hrms.emps.dao.*;
import senior.hrms.emps.factory.*;
import senior.hrms.emps.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Religion implements Serializable
{
	/** 
	 * This attribute maps to the column RELIGION_ID in the RELIGION table.
	 */
	protected int religionId;

	/** 
	 * This attribute maps to the column RELIGION_NAME in the RELIGION table.
	 */
	protected String religionName;

	/**
	 * Method 'Religion'
	 * 
	 */
	public Religion()
	{
	}

	/**
	 * Method 'getReligionId'
	 * 
	 * @return int
	 */
	public int getReligionId()
	{
		return religionId;
	}

	/**
	 * Method 'setReligionId'
	 * 
	 * @param religionId
	 */
	public void setReligionId(int religionId)
	{
		this.religionId = religionId;
	}

	/**
	 * Method 'getReligionName'
	 * 
	 * @return String
	 */
	public String getReligionName()
	{
		return religionName;
	}

	/**
	 * Method 'setReligionName'
	 * 
	 * @param religionName
	 */
	public void setReligionName(String religionName)
	{
		this.religionName = religionName;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Religion)) {
			return false;
		}
		
		final Religion _cast = (Religion) _other;
		if (religionId != _cast.religionId) {
			return false;
		}
		
		if (religionName == null ? _cast.religionName != religionName : !religionName.equals( _cast.religionName )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + religionId;
		if (religionName != null) {
			_hashCode = 29 * _hashCode + religionName.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ReligionPk
	 */
	public ReligionPk createPk()
	{
		return new ReligionPk(religionId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "senior.hrms.emps.dto.Religion: " );
		ret.append( "religionId=" + religionId );
		ret.append( ", religionName=" + religionName );
		return ret.toString();
	}

}
