/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the ROLES table.
 */
public class RolesPk implements Serializable
{
	protected int roleId;

	/** 
	 * This attribute represents whether the primitive attribute roleId is null.
	 */
	protected boolean roleIdNull;

	/** 
	 * Sets the value of roleId
	 */
	public void setRoleId(int roleId)
	{
		this.roleId = roleId;
	}

	/** 
	 * Gets the value of roleId
	 */
	public int getRoleId()
	{
		return roleId;
	}

	/**
	 * Method 'RolesPk'
	 * 
	 */
	public RolesPk()
	{
	}

	/**
	 * Method 'RolesPk'
	 * 
	 * @param roleId
	 */
	public RolesPk(final int roleId)
	{
		this.roleId = roleId;
	}

	/** 
	 * Sets the value of roleIdNull
	 */
	public void setRoleIdNull(boolean roleIdNull)
	{
		this.roleIdNull = roleIdNull;
	}

	/** 
	 * Gets the value of roleIdNull
	 */
	public boolean isRoleIdNull()
	{
		return roleIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof RolesPk)) {
			return false;
		}
		
		final RolesPk _cast = (RolesPk) _other;
		if (roleId != _cast.roleId) {
			return false;
		}
		
		if (roleIdNull != _cast.roleIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + roleId;
		_hashCode = 29 * _hashCode + (roleIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "senior.hrms.emps.dto.RolesPk: " );
		ret.append( "roleId=" + roleId );
		return ret.toString();
	}

}
