/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dto;

import senior.hrms.emps.dao.*;
import senior.hrms.emps.factory.*;
import senior.hrms.emps.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class UsersRoles implements Serializable
{
	/** 
	 * This attribute maps to the column USER_ROLE_ID in the USERS_ROLES table.
	 */
	protected int userRoleId;

	/** 
	 * This attribute maps to the column USER_ID in the USERS_ROLES table.
	 */
	protected int userId;

	/** 
	 * This attribute maps to the column ROLE_ID in the USERS_ROLES table.
	 */
	protected int roleId;

	/** 
	 * This attribute maps to the column DESCRIPTION in the USERS_ROLES table.
	 */
	protected String description;

	/**
	 * Method 'UsersRoles'
	 * 
	 */
	public UsersRoles()
	{
	}

	/**
	 * Method 'getUserRoleId'
	 * 
	 * @return int
	 */
	public int getUserRoleId()
	{
		return userRoleId;
	}

	/**
	 * Method 'setUserRoleId'
	 * 
	 * @param userRoleId
	 */
	public void setUserRoleId(int userRoleId)
	{
		this.userRoleId = userRoleId;
	}

	/**
	 * Method 'getUserId'
	 * 
	 * @return int
	 */
	public int getUserId()
	{
		return userId;
	}

	/**
	 * Method 'setUserId'
	 * 
	 * @param userId
	 */
	public void setUserId(int userId)
	{
		this.userId = userId;
	}

	/**
	 * Method 'getRoleId'
	 * 
	 * @return int
	 */
	public int getRoleId()
	{
		return roleId;
	}

	/**
	 * Method 'setRoleId'
	 * 
	 * @param roleId
	 */
	public void setRoleId(int roleId)
	{
		this.roleId = roleId;
	}

	/**
	 * Method 'getDescription'
	 * 
	 * @return String
	 */
	public String getDescription()
	{
		return description;
	}

	/**
	 * Method 'setDescription'
	 * 
	 * @param description
	 */
	public void setDescription(String description)
	{
		this.description = description;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof UsersRoles)) {
			return false;
		}
		
		final UsersRoles _cast = (UsersRoles) _other;
		if (userRoleId != _cast.userRoleId) {
			return false;
		}
		
		if (userId != _cast.userId) {
			return false;
		}
		
		if (roleId != _cast.roleId) {
			return false;
		}
		
		if (description == null ? _cast.description != description : !description.equals( _cast.description )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + userRoleId;
		_hashCode = 29 * _hashCode + userId;
		_hashCode = 29 * _hashCode + roleId;
		if (description != null) {
			_hashCode = 29 * _hashCode + description.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return UsersRolesPk
	 */
	public UsersRolesPk createPk()
	{
		return new UsersRolesPk(userRoleId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "senior.hrms.emps.dto.UsersRoles: " );
		ret.append( "userRoleId=" + userRoleId );
		ret.append( ", userId=" + userId );
		ret.append( ", roleId=" + roleId );
		ret.append( ", description=" + description );
		return ret.toString();
	}

}
