/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package senior.hrms.emps.dto;

import senior.hrms.emps.dao.*;
import senior.hrms.emps.factory.*;
import senior.hrms.emps.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class VacationRequestStatus implements Serializable
{
	/** 
	 * This attribute maps to the column VACATION_REQUEST_STATUS_ID in the VACATION_REQUEST_STATUS table.
	 */
	protected int vacationRequestStatusId;

	/** 
	 * This attribute maps to the column VACATION_REQUEST_STATUS_NAME in the VACATION_REQUEST_STATUS table.
	 */
	protected String vacationRequestStatusName;

	/**
	 * Method 'VacationRequestStatus'
	 * 
	 */
	public VacationRequestStatus()
	{
	}

	/**
	 * Method 'getVacationRequestStatusId'
	 * 
	 * @return int
	 */
	public int getVacationRequestStatusId()
	{
		return vacationRequestStatusId;
	}

	/**
	 * Method 'setVacationRequestStatusId'
	 * 
	 * @param vacationRequestStatusId
	 */
	public void setVacationRequestStatusId(int vacationRequestStatusId)
	{
		this.vacationRequestStatusId = vacationRequestStatusId;
	}

	/**
	 * Method 'getVacationRequestStatusName'
	 * 
	 * @return String
	 */
	public String getVacationRequestStatusName()
	{
		return vacationRequestStatusName;
	}

	/**
	 * Method 'setVacationRequestStatusName'
	 * 
	 * @param vacationRequestStatusName
	 */
	public void setVacationRequestStatusName(String vacationRequestStatusName)
	{
		this.vacationRequestStatusName = vacationRequestStatusName;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof VacationRequestStatus)) {
			return false;
		}
		
		final VacationRequestStatus _cast = (VacationRequestStatus) _other;
		if (vacationRequestStatusId != _cast.vacationRequestStatusId) {
			return false;
		}
		
		if (vacationRequestStatusName == null ? _cast.vacationRequestStatusName != vacationRequestStatusName : !vacationRequestStatusName.equals( _cast.vacationRequestStatusName )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + vacationRequestStatusId;
		if (vacationRequestStatusName != null) {
			_hashCode = 29 * _hashCode + vacationRequestStatusName.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return VacationRequestStatusPk
	 */
	public VacationRequestStatusPk createPk()
	{
		return new VacationRequestStatusPk(vacationRequestStatusId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "senior.hrms.emps.dto.VacationRequestStatus: " );
		ret.append( "vacationRequestStatusId=" + vacationRequestStatusId );
		ret.append( ", vacationRequestStatusName=" + vacationRequestStatusName );
		return ret.toString();
	}

}
