/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */
package settings.handler.general;

import senior.hrms.emps.dto.*;
import senior.hrms.emps.exceptions.*;

public interface AccidentTypesInterface
{

    public AccidentTypesPk addAccidentTypes(AccidentTypes dto) throws AccidentTypesDaoException;

    public void updateAccidentTypes(AccidentTypesPk pk, AccidentTypes dto) throws AccidentTypesDaoException;

    public void deleteAccidentTypes(AccidentTypesPk pk) throws AccidentTypesDaoException;

    public AccidentTypes getAccidentTypesById(int accidentTypeId) throws AccidentTypesDaoException;

    public AccidentTypes[] getAllAccidentTypes() throws AccidentTypesDaoException;

    public AccidentTypes[] getAccidentTypeByName(String accidentType) throws AccidentTypesDaoException;

}
