/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */
package settings.handler.general;

import senior.hrms.emps.dto.*;
import senior.hrms.emps.exceptions.*;

public interface BusLineAreasInterface
{

    public BusLineAreasPk addBusLineAreas(BusLineAreas dto) throws BusLineAreasDaoException;

    public void updateBusLineAreas(BusLineAreasPk pk, BusLineAreas dto) throws BusLineAreasDaoException;

    public void deleteBusLineAreas(BusLineAreasPk pk) throws BusLineAreasDaoException;

    public BusLineAreas getBusLineAreasById(int busLineAreaId) throws BusLineAreasDaoException;

    public BusLineAreas[] getAllBusLineAreas() throws BusLineAreasDaoException;

    public BusLineAreas[] getBusLineAreaByName(String busLineAreaName) throws BusLineAreasDaoException;

}
