/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */
package settings.handler.general;

import senior.hrms.emps.dto.*;
import senior.hrms.emps.exceptions.*;

public interface DiseaseTypesInterface
{

    public DiseaseTypesPk addDiseaseTypes(DiseaseTypes dto) throws DiseaseTypesDaoException;

    public void updateDiseaseTypes(DiseaseTypesPk pk, DiseaseTypes dto) throws DiseaseTypesDaoException;

    public void deleteDiseaseTypes(DiseaseTypesPk pk) throws DiseaseTypesDaoException;

    public DiseaseTypes[] getDiseaseTypesById(int diseaseTypeId) throws DiseaseTypesDaoException;

    public DiseaseTypes[] getAllDiseaseTypes() throws DiseaseTypesDaoException;

    public DiseaseTypes[] getDiseaseTypeByName(String diseaseTypeName) throws DiseaseTypesDaoException;

}
