/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */
package settings.handler.general;

import senior.hrms.emps.dto.*;
import senior.hrms.emps.exceptions.*;

public interface MaritalStatusInterface
{

    public MaritalStatusPk addMaritalStatus(MaritalStatus dto) throws MaritalStatusDaoException;

    public void updateMaritalStatus(MaritalStatusPk pk, MaritalStatus dto) throws MaritalStatusDaoException;

    public void deleteMaritalStatus(MaritalStatusPk pk) throws MaritalStatusDaoException;

    public MaritalStatus getMaritalStatusById(int maritalStatusId) throws MaritalStatusDaoException;

    public MaritalStatus[] getAllMaritalStatus() throws MaritalStatusDaoException;

    public MaritalStatus[] getMaritalStatusByName(String maritalStatusName) throws MaritalStatusDaoException;

}
