/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */
package settings.handler.general;

import senior.hrms.emps.dto.*;
import senior.hrms.emps.exceptions.*;

public interface ReligionInterface
{

    public ReligionPk addReligion(Religion dto) throws ReligionDaoException;

    public void updateReligion(ReligionPk pk, Religion dto) throws ReligionDaoException;

    public void deleteReligion(ReligionPk pk) throws ReligionDaoException;

    public Religion getReligionById(int religionId) throws ReligionDaoException;

    public Religion[] getAllReligion() throws ReligionDaoException;

    public Religion[] getReligionByName(String religionName) throws ReligionDaoException;

}
