/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */
package settings.handler.affairs;

import senior.hrms.emps.dto.*;
import senior.hrms.emps.exceptions.*;

public interface MissionSidesInterface
{

    public MissionSidesPk addMissionSides(MissionSides dto) throws MissionSidesDaoException;

    public void updateMissionSides(MissionSidesPk pk, MissionSides dto) throws MissionSidesDaoException;

    public void deleteMissionSides(MissionSidesPk pk) throws MissionSidesDaoException;

    public MissionSides getMissionSidesById(int missionSideId) throws MissionSidesDaoException;

    public MissionSides[] getAllMissionSides() throws MissionSidesDaoException;

    public MissionSides[] getMissionSideByName(String missionSideName) throws MissionSidesDaoException;

}
