

package settings.forms.general;

import com.Common;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import senior.hrms.emps.dto.AccidentTypes;
import senior.hrms.emps.dto.AccidentTypesPk;
import senior.hrms.emps.exceptions.AccidentTypesDaoException;
import settings.handler.general.AccidentTypesHandler;

/**
 *
 * @author amal
 */
public class AccedentTypes extends javax.swing.JFrame
{
    Common comObj;
    /**
     * Creates new form AccedentTypes
     */
    public AccedentTypes() throws AccidentTypesDaoException
    {
        initComponents();
        
        comObj = new Common();
        
        // Max frame width //
        int width =Integer.parseInt( comObj.resourceFile.getString("innerFrameSize") );
        comObj.setMaxFrameWidth(this, width);
        
         newNameLabel.setVisible(false);
        ButtonConfirm.setVisible(false);
        textfieldUpdate.setVisible(false);
        update.setVisible(false);
        cancelButton.setVisible(false);
            // put data into table
        AccidentTypesHandler oh = new AccidentTypesHandler ();
        AccidentTypes[] list = oh.getAllAccidentTypes();
        DefaultTableModel dtm = (DefaultTableModel) showTable.getModel();
        dtm.setRowCount(0);
        for(int i=0;i<list.length;i++)
        {
        AccidentTypes or = list[i];
        Vector row= new Vector();
        row.add(or.getAccidentType());
        row.add(or.getAccidentTypeId());
        dtm.addRow(row);
        
        }
        showTable.setModel(dtm);
        showTable.updateUI();
         jScrollPane1.setViewportView(showTable);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label1 = new javax.swing.JLabel();
        TextFieldSearch = new javax.swing.JTextField();
        showAll = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showTable = new javax.swing.JTable();
        ButtonUpdate = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();
        newNameLabel = new javax.swing.JLabel();
        textfieldUpdate = new javax.swing.JTextField();
        ButtonConfirm = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        update = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label1.setText("أنواع الحوادث");
        Label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Label1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        showAll.setText("عرض الكل");
        showAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllActionPerformed(evt);
            }
        });

        addButton.setText("اضافة جديد");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        SearchButton.setText("بحث");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        showTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "الاسم", "المسلسل"
            }
        ));
        jScrollPane1.setViewportView(showTable);

        ButtonUpdate.setText("اختر للتحديث");
        ButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUpdateActionPerformed(evt);
            }
        });

        ButtonDelete.setText("حذف");
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        newNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        newNameLabel.setText("الاسم الجديد");

        ButtonConfirm.setText("تعديل");
        ButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfirmActionPerformed(evt);
            }
        });

        cancelButton.setText("الغاء");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update.setForeground(new java.awt.Color(255, 0, 0));
        update.setText("تم الحفظ بنجاح");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)
                                .addComponent(ButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(showAll, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(textfieldUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(newNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(70, 70, 70))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showAll, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonConfirm)
                    .addComponent(cancelButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
    newNameLabel.setVisible(false);
        ButtonConfirm.setVisible(false);
        textfieldUpdate.setVisible(false);
         cancelButton.setVisible(false);
         if(TextFieldSearch.getText().length() == 0)
        {
         update.setVisible(false);
        }
        else 
        {
            try{
         String keyword = TextFieldSearch.getText();
         AccidentTypes dto =new AccidentTypes();
         dto.setAccidentType(keyword);
         AccidentTypesHandler oh = new AccidentTypesHandler();
         oh.addAccidentTypes(dto);
         update.setText("تم الاضافه بنجاح");
         update.setVisible(true);
            }
            catch(Exception ex){  }
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void showAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllActionPerformed
       try{
        newNameLabel.setVisible(false);
        ButtonConfirm.setVisible(false);
        textfieldUpdate.setVisible(false);
        update.setVisible(false);
        cancelButton.setVisible(false);
            // put data into table
        AccidentTypesHandler oh = new AccidentTypesHandler ();
        AccidentTypes[] list = oh.getAllAccidentTypes();
        DefaultTableModel dtm = (DefaultTableModel) showTable.getModel();
        dtm.setRowCount(0);
        for(int i=0;i<list.length;i++)
        {
        AccidentTypes or = list[i];
        Vector row= new Vector();
        row.add(or.getAccidentType());
        row.add(or.getAccidentTypeId());
        dtm.addRow(row);
        
        }
        showTable.setModel(dtm);
        showTable.updateUI();
         jScrollPane1.setViewportView(showTable);
       }
       catch(Exception ex)
       {}
        // TODO add your handling code here:
    }//GEN-LAST:event_showAllActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
    newNameLabel.setVisible(false);
        ButtonConfirm.setVisible(false);
        textfieldUpdate.setVisible(false);
        cancelButton.setVisible(false);
        update.setVisible(false);
        
         try{
        String keyword = TextFieldSearch.getText();
        AccidentTypesHandler oh = new AccidentTypesHandler();
        AccidentTypes[] list = oh.getAccidentTypeByName(keyword);
           
        DefaultTableModel dtm = (DefaultTableModel) showTable.getModel();
        dtm.setRowCount(0);
        for(int i=0;i<list.length;i++)
        {
        AccidentTypes or = list[i];
        Vector row= new Vector();
         row.add(or.getAccidentType());
        row.add(or.getAccidentTypeId());
        dtm.addRow(row);
        
        }
        showTable.setModel(dtm);
        showTable.updateUI();
        jScrollPane1.setViewportView(showTable);
            }
            catch(Exception ex) {}
       
// TODO add your handling code here:
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed

       try{  
        if(showTable.getSelectedRow()>=0)
         {
       newNameLabel.setVisible(false);
        ButtonConfirm.setVisible(false);
        textfieldUpdate.setVisible(false);
        cancelButton.setVisible(false);
   int row = showTable.getSelectedRow();
   int culumn = 1;
   int valueOfId = Integer.parseInt(showTable.getValueAt(row, culumn).toString());
    int confirm= JOptionPane.showConfirmDialog(rootPane, "هل انت متاكد بالحذف !");
         if(confirm==0)
         {
        AccidentTypes or=new AccidentTypes();
        or.setAccidentTypeId(valueOfId);
        AccidentTypesPk pk=or.createPk();
        AccidentTypesHandler oh = new AccidentTypesHandler();
        oh.deleteAccidentTypes(pk);
         JOptionPane.showMessageDialog(rootPane,"تم الحذف بنجاح");
          newNameLabel.setVisible(false);
        ButtonConfirm.setVisible(false);
        textfieldUpdate.setVisible(false);
        cancelButton.setVisible(false);
         }
         }
       }
       catch(Exception ex){}
   
 
    
// TODO add your handling code here:
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void ButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUpdateActionPerformed

 if(showTable.getSelectedRow()>=0)
   {
        newNameLabel.setVisible(true);
        ButtonConfirm.setVisible(true);
        cancelButton.setVisible(true);
        textfieldUpdate.setVisible(true);
        update.setVisible(false);
   }        
// TODO add your handling code here:
    }//GEN-LAST:event_ButtonUpdateActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    newNameLabel.setVisible(false);
        ButtonConfirm.setVisible(false);
        textfieldUpdate.setVisible(false);
        textfieldUpdate.setText("");
        cancelButton.setVisible(false);
        
        update.setVisible(false);
        
// TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void ButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfirmActionPerformed
      try{
        if(showTable.getSelectedRow()>=0)
   {
   int row = showTable.getSelectedRow();
   int culumn = 1;
   int valueOfId = Integer.parseInt(showTable.getValueAt(row, culumn).toString());
   String newName = textfieldUpdate.getText();
        AccidentTypes or=new AccidentTypes();
        or.setAccidentTypeId(valueOfId);
        or.setAccidentType(newName);
        AccidentTypesPk pk=or.createPk();
        AccidentTypesHandler oh = new AccidentTypesHandler();
        oh.updateAccidentTypes(pk, or);
        newNameLabel.setVisible(false);
        ButtonConfirm.setVisible(false);
        cancelButton.setVisible(false);
        textfieldUpdate.setVisible(false);
        update.setVisible(true);
        update.setText("تم التعديل بنجاح");
        }
        }
        catch(Exception ex){  }
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(AccedentTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(AccedentTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(AccedentTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(AccedentTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                try {
                    new AccedentTypes().setVisible(true);
                } catch (AccidentTypesDaoException ex) {
                    Logger.getLogger(AccedentTypes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonConfirm;
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonUpdate;
    private javax.swing.JLabel Label1;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField TextFieldSearch;
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel newNameLabel;
    private javax.swing.JButton showAll;
    private javax.swing.JTable showTable;
    private javax.swing.JTextField textfieldUpdate;
    private javax.swing.JLabel update;
    // End of variables declaration//GEN-END:variables
}

