

package settings.forms.general;

import com.Common;
import static java.util.Collections.list;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.beans.binding.Bindings.or;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import senior.hrms.emps.dto.DiseaseTypes;
import senior.hrms.emps.dto.Diseases;
import senior.hrms.emps.dto.DiseasesPk;
import senior.hrms.emps.exceptions.DiseaseTypesDaoException;
import senior.hrms.emps.exceptions.DiseasesDaoException;
import settings.handler.general.DiseaseTypesHandler;
import settings.handler.general.DiseasesHandler;

/**
 *
 * @author amal
 */
public class Disease extends javax.swing.JFrame
{
    Common comObj;

    /**
     * Creates new form Disease
     */
    public Disease() throws DiseasesDaoException, DiseaseTypesDaoException
    {
        initComponents();
        
         comObj = new Common();
        
        // Max frame width //
        int width =Integer.parseInt( comObj.resourceFile.getString("innerFrameSize") );
         comObj.setMaxFrameWidth(this, width);
         
         try{
          NameTextField.setVisible(false);
         resultTextField.setVisible(false);
         cancelNewButton.setVisible(false);
         cancelUpdateButton.setVisible(false);
         confirmNewButton.setVisible(false);
         confirmUpdateButton.setVisible(false);
         nameLabel.setVisible(false);
         newNameTextField.setVisible(false);
         newresultTextField.setVisible(false);
         newnameLabel.setVisible(false);
         typeLabel.setVisible(false);
         newtypeLabel.setVisible(false);
         resultLabel.setVisible(false);
         newresultLabel.setVisible(false);
         typeComboBox.setVisible(false);
         newtypeComboBox.setVisible(false);
         update.setVisible(false);
         
         
          typeComboBox.removeAllItems();
         newtypeComboBox.removeAllItems();
           DiseaseTypesHandler dtHandler = new  DiseaseTypesHandler();
            DiseaseTypes[] diseasetype  = dtHandler.getAllDiseaseTypes();
       
        typeComboBox.addItem("-Choose-");
        newtypeComboBox.addItem("-Choose-");
        for(int i=0;i<diseasetype.length;i++)
        {
        DiseaseTypes or = diseasetype[i];
        typeComboBox.addItem(or.getDiseaseTypeName());
        newtypeComboBox.addItem(or.getDiseaseTypeName());  
        
        }
         
         
          DiseasesHandler oh = new DiseasesHandler();
        Diseases[] list =  oh.getAllDiseases();
        DefaultTableModel dtm = (DefaultTableModel) showTable.getModel();
        dtm.setRowCount(0);
        for(int i=0;i<list.length;i++)
        {
              Diseases or = list[i];
           String typeName="";
              int typeId=or.getDiseaseTypeId();
             if(typeId == 0)
             {
            
            typeName = "  ";
             }
             else
             {
//              
             DiseaseTypesHandler dth = new  DiseaseTypesHandler();
            DiseaseTypes[] dt  = dth.getDiseaseTypesById(typeId);
            typeName = dt[0].getDiseaseTypeName();
             }
           
        
            Vector row= new Vector();
            row.add(typeName);
            row.add(or.getResult());
            row.add(or.getDiseaseName()); 
            row.add(or.getDiseaseId());
        
            dtm.addRow(row);
        
        }
        showTable.setModel(dtm);
        showTable.updateUI();
         jScrollPane1.setViewportView(showTable);
    }
    catch(Exception ex){ }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label1 = new javax.swing.JLabel();
        showAll = new javax.swing.JButton();
        addNewButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        resultLabel = new javax.swing.JLabel();
        resultTextField = new javax.swing.JTextField();
        typeLabel = new javax.swing.JLabel();
        TextFieldSearch = new javax.swing.JTextField();
        cancelNewButton = new javax.swing.JButton();
        confirmNewButton = new javax.swing.JButton();
        typeComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        showTable = new javax.swing.JTable();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        newnameLabel = new javax.swing.JLabel();
        newNameTextField = new javax.swing.JTextField();
        newresultLabel = new javax.swing.JLabel();
        newresultTextField = new javax.swing.JTextField();
        newtypeLabel = new javax.swing.JLabel();
        newtypeComboBox = new javax.swing.JComboBox();
        confirmUpdateButton = new javax.swing.JButton();
        cancelUpdateButton = new javax.swing.JButton();
        update = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label1.setText("ألامراض");

        showAll.setText("عرض الكل");
        showAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllActionPerformed(evt);
            }
        });

        addNewButton.setText("اضافة جديد");
        addNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewButtonActionPerformed(evt);
            }
        });

        searchButton.setText("بحث");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("الاسم");

        resultLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        resultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultLabel.setText("النتيجة");

        typeLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        typeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typeLabel.setText("النوع");

        cancelNewButton.setText("الغاء");
        cancelNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelNewButtonActionPerformed(evt);
            }
        });

        confirmNewButton.setText("اضافة");
        confirmNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmNewButtonActionPerformed(evt);
            }
        });

        showTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "النوع", "النتيجة", "الاسم", "مسلسل"
            }
        ));
        jScrollPane1.setViewportView(showTable);

        updateButton.setText("اخترللتحديث");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("حذف");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        newnameLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        newnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newnameLabel.setText("الاسم");

        newresultLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        newresultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newresultLabel.setText("النتيجة");

        newtypeLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        newtypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newtypeLabel.setText("النوع");

        confirmUpdateButton.setText("تعديل");
        confirmUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmUpdateButtonActionPerformed(evt);
            }
        });

        cancelUpdateButton.setText("الغاء");
        cancelUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelUpdateButtonActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update.setForeground(new java.awt.Color(255, 0, 0));
        update.setText("تم الحفظ بنجاح");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addNewButton)
                        .addGap(18, 18, 18)
                        .addComponent(showAll, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelNewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(confirmNewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 34, Short.MAX_VALUE)
                .addComponent(cancelUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newtypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(newtypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(newresultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newresultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showAll)
                    .addComponent(addNewButton)
                    .addComponent(searchButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelNewButton)
                    .addComponent(confirmNewButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newresultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newresultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newtypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newtypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelUpdateButton)
                    .addComponent(confirmUpdateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllActionPerformed
       
    try{
      NameTextField.setVisible(false);
         resultTextField.setVisible(false);
         cancelNewButton.setVisible(false);
         cancelUpdateButton.setVisible(false);
         confirmNewButton.setVisible(false);
         confirmUpdateButton.setVisible(false);
         nameLabel.setVisible(false);
         newNameTextField.setVisible(false);
         newresultTextField.setVisible(false);
         newnameLabel.setVisible(false);
         typeLabel.setVisible(false);
         newtypeLabel.setVisible(false);
         resultLabel.setVisible(false);
         newresultLabel.setVisible(false);
         typeComboBox.setVisible(false);
         newtypeComboBox.setVisible(false);
         update.setVisible(false);
         
         
          typeComboBox.removeAllItems();
         newtypeComboBox.removeAllItems();
           DiseaseTypesHandler dtHandler = new  DiseaseTypesHandler();
            DiseaseTypes[] diseasetype  = dtHandler.getAllDiseaseTypes();
       
        typeComboBox.addItem("-Choose-");
        newtypeComboBox.addItem("-Choose-");
        for(int i=0;i<diseasetype.length;i++)
        {
        senior.hrms.emps.dto.DiseaseTypes or = diseasetype[i];
        typeComboBox.addItem(or.getDiseaseTypeName());
        newtypeComboBox.addItem(or.getDiseaseTypeName());  
        
        }
         
         
          DiseasesHandler oh = new DiseasesHandler();
        senior.hrms.emps.dto.Diseases[] list = (senior.hrms.emps.dto.Diseases[]) oh.getAllDiseases();
        DefaultTableModel dtm = (DefaultTableModel) showTable.getModel();
        dtm.setRowCount(0);
        for(int i=0;i<list.length;i++)
        {
                 Diseases or = list[i];
           String typeName="";
              int typeId=or.getDiseaseTypeId();
             if(typeId == 0)
             {
            
            typeName = "  ";
             }
             else
             {
//              
             DiseaseTypesHandler dth = new  DiseaseTypesHandler();
            DiseaseTypes[] dt  = dth.getDiseaseTypesById(typeId);
            typeName = dt[0].getDiseaseTypeName();
             }
           
        
            Vector row= new Vector();
            row.add(typeName);
            row.add(or.getResult());
            row.add(or.getDiseaseName()); 
            row.add(or.getDiseaseId());
        
            dtm.addRow(row);
        }
        showTable.setModel(dtm);
        showTable.updateUI();
         jScrollPane1.setViewportView(showTable);
    }
    catch(Exception ex){ }

    
        // TODO add your handling code here:
    }//GEN-LAST:event_showAllActionPerformed

    private void addNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewButtonActionPerformed
         NameTextField.setVisible(true);
         resultTextField.setVisible(true);
         cancelNewButton.setVisible(true);
         cancelUpdateButton.setVisible(false);
         confirmNewButton.setVisible(true);
         confirmUpdateButton.setVisible(false);
         nameLabel.setVisible(true);
         newNameTextField.setVisible(false);
         newresultTextField.setVisible(false);
         newnameLabel.setVisible(false);
         typeLabel.setVisible(true);
         newtypeLabel.setVisible(false);
         resultLabel.setVisible(true);
         newresultLabel.setVisible(false);
         typeComboBox.setVisible(true);
         newtypeComboBox.setVisible(false);
         update.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_addNewButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
       try{
        NameTextField.setVisible(false);
         resultTextField.setVisible(false);
         cancelNewButton.setVisible(false);
         cancelUpdateButton.setVisible(false);
         confirmNewButton.setVisible(false);
         confirmUpdateButton.setVisible(false);
         nameLabel.setVisible(false);
         newNameTextField.setVisible(false);
         newresultTextField.setVisible(false);
         newnameLabel.setVisible(false);
         typeLabel.setVisible(false);
         newtypeLabel.setVisible(false);
         resultLabel.setVisible(false);
         newresultLabel.setVisible(false);
         typeComboBox.setVisible(false);
         newtypeComboBox.setVisible(false);
         update.setVisible(false);
         String keyword = TextFieldSearch.getText();
          DiseasesHandler oh = new DiseasesHandler();
        senior.hrms.emps.dto.Diseases[] list = (senior.hrms.emps.dto.Diseases[]) oh.getDiseaseByName(keyword);
        DefaultTableModel dtm = (DefaultTableModel) showTable.getModel();
        dtm.setRowCount(0);
        for(int i=0;i<list.length;i++)
        {
              senior.hrms.emps.dto.Diseases or = list[i];
              int typeId=or.getDiseaseTypeId();
              
             DiseaseTypesHandler dth = new  DiseaseTypesHandler();
            senior.hrms.emps.dto.DiseaseTypes[] dt  = dth.getDiseaseTypesById(typeId);
            String typeName = dt[0].getDiseaseTypeName();
        
            Vector row= new Vector();
            row.add(typeName);
            row.add(or.getResult());
            row.add(or.getDiseaseName());
            row.add(or.getDiseaseId());
        
            dtm.addRow(row);
        
        }
        showTable.setModel(dtm);
        showTable.updateUI();
         jScrollPane1.setViewportView(showTable);
       }
       catch(Exception ex){ }

    
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void cancelNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelNewButtonActionPerformed
         NameTextField.setVisible(false);
         resultTextField.setVisible(false);
         cancelNewButton.setVisible(false);
         confirmNewButton.setVisible(false);
         nameLabel.setVisible(false);
         typeLabel.setVisible(false);
         resultLabel.setVisible(false);
         typeComboBox.setVisible(false);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelNewButtonActionPerformed

    private void confirmNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmNewButtonActionPerformed
     try{
        if(NameTextField.getText().length()==0)
   {
       JOptionPane.showMessageDialog(rootPane,"يجب ان تدخل الاسم");
   }
     else
     {
     if(typeComboBox.getSelectedIndex()==0)
     {
         String name= NameTextField.getText();
         String result = resultTextField.getText();
         senior.hrms.emps.dto.Diseases dto =new senior.hrms.emps.dto.Diseases();
         
         dto.setDiseaseName(name);
         dto.setResult(result);
         
         DiseasesHandler oh = new DiseasesHandler();
         oh.addDiseases(dto);
         update.setText("تم الاضافه بنجاح");
         update.setVisible(true);
        NameTextField.setText("");
        NameTextField.setText("");
        resultTextField.setText("");
     }
     
     if(typeComboBox.getSelectedIndex()> 0)
     {
            String typeNameFromCompo = typeComboBox.getSelectedItem().toString();
            DiseaseTypesHandler dth = new  DiseaseTypesHandler();
            DiseaseTypes[] dt  = dth.getDiseaseTypeByName(typeNameFromCompo);
           
            int typeID = dt[0].getDiseaseTypeId();
         
         String name= NameTextField.getText();
         String result = resultTextField.getText();
         senior.hrms.emps.dto.Diseases dto =new senior.hrms.emps.dto.Diseases();
         
         dto.setDiseaseName(name);
         dto.setResult(result);
         dto.setDiseaseTypeId(typeID);
         
         DiseasesHandler oh = new DiseasesHandler();
         oh.addDiseases(dto);
         update.setText("تم الاضافه بنجاح");
         update.setVisible(true);
        NameTextField.setText("");
        NameTextField.setText("");
        resultTextField.setText("");
     }
   
     }
     }
     catch(Exception ex){ }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmNewButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        if(showTable.getSelectedRow()>=0)
        {
         NameTextField.setVisible(false);
         resultTextField.setVisible(false);
         cancelNewButton.setVisible(false);
         cancelUpdateButton.setVisible(true);
         confirmNewButton.setVisible(false);
         confirmUpdateButton.setVisible(true);
         nameLabel.setVisible(false);
         newNameTextField.setVisible(true);
         newresultTextField.setVisible(true);
         newnameLabel.setVisible(true);
         typeLabel.setVisible(false);
         newtypeLabel.setVisible(true);
         resultLabel.setVisible(false);
         newresultLabel.setVisible(true);
         typeComboBox.setVisible(false);
         newtypeComboBox.setVisible(true);
         update.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try{
            if(showTable.getSelectedRow()>=0)
            {
                NameTextField.setVisible(false);
         resultTextField.setVisible(false);
         cancelNewButton.setVisible(false);
         cancelUpdateButton.setVisible(false);
         confirmNewButton.setVisible(false);
         confirmUpdateButton.setVisible(false);
         nameLabel.setVisible(false);
         newNameTextField.setVisible(false);
         newresultTextField.setVisible(false);
         newnameLabel.setVisible(false);
         typeLabel.setVisible(false);
         newtypeLabel.setVisible(false);
         resultLabel.setVisible(false);
         newresultLabel.setVisible(false);
         typeComboBox.setVisible(false);
         newtypeComboBox.setVisible(false);
         update.setVisible(false);
                int row = showTable.getSelectedRow();
                int culumn = 3;
                int valueOfId = Integer.parseInt(showTable.getValueAt(row, culumn).toString());
                int confirm= JOptionPane.showConfirmDialog(rootPane, "هل انت متاكد بالحذف !");
                if(confirm==0)
                {
                    senior.hrms.emps.dto.Diseases or=new senior.hrms.emps.dto.Diseases();
                    or.setDiseaseId(valueOfId);
                    DiseasesPk pk=or.createPk();
                    DiseasesHandler oh = new DiseasesHandler();
                    oh.deleteDiseases(pk);
                    JOptionPane.showMessageDialog(rootPane,"تم الحذف بنجاح");
                }
            }
        }
        catch(Exception ex){}

        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void confirmUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmUpdateButtonActionPerformed
  try{
       if(newNameTextField.getText().length()==0)
      {
            JOptionPane.showMessageDialog(rootPane,"يجب ان تدخل الاسم");
      }
     else
     {
               if(newtypeComboBox.getSelectedIndex()== 0)
                {
                int row = showTable.getSelectedRow();
                int culumn = 3;
                int valueOfId = Integer.parseInt(showTable.getValueAt(row, culumn).toString());
         
               String name= newNameTextField.getText();
               String result = newresultTextField.getText();
               senior.hrms.emps.dto.Diseases dto =new senior.hrms.emps.dto.Diseases();
               dto.setDiseaseId(valueOfId);
               dto.setDiseaseName(name);
               dto.setResult(result);
               DiseasesPk pk= dto.createPk();
         
              DiseasesHandler oh = new DiseasesHandler();
              oh.updateDiseases(pk, dto);
              update.setText("تم التعديل بنجاح");
             update.setVisible(true);
             newNameTextField.setText("");
              newNameTextField.setText("");
              newresultTextField.setText("");
             }
     
               if(newtypeComboBox.getSelectedIndex()> 0)
               {
         
               int row = showTable.getSelectedRow();
                int culumn = 3;
                int valueOfId = Integer.parseInt(showTable.getValueAt(row, culumn).toString());
            String typeNameFromCompo = newtypeComboBox.getSelectedItem().toString();
            DiseaseTypesHandler dth = new  DiseaseTypesHandler();
            DiseaseTypes[] dt  = dth.getDiseaseTypeByName(typeNameFromCompo);
           
            int typeID = dt[0].getDiseaseTypeId();
                
         
            String name= newNameTextField.getText();
             String result = newresultTextField.getText();
            Diseases dto =new Diseases();
            dto.setDiseaseId(valueOfId);
            dto.setDiseaseName(name);
            dto.setResult(result);
            dto.setDiseaseTypeId(typeID);
            DiseasesPk pk= dto.createPk();
            DiseasesHandler oh = new DiseasesHandler();
            oh.updateDiseases(pk, dto);
            update.setText("تم التعديل بنجاح");
            update.setVisible(true);
            newNameTextField.setText("");
            newNameTextField.setText("");
            newresultTextField.setText("");
             }
     }
     }
     catch(Exception ex){ }
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmUpdateButtonActionPerformed

    private void cancelUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelUpdateButtonActionPerformed

        NameTextField.setVisible(false);
         resultTextField.setVisible(false);
         cancelNewButton.setVisible(false);
         cancelUpdateButton.setVisible(false);
         confirmNewButton.setVisible(false);
         confirmUpdateButton.setVisible(false);
         nameLabel.setVisible(false);
         newNameTextField.setVisible(false);
         newresultTextField.setVisible(false);
         newnameLabel.setVisible(false);
         typeLabel.setVisible(false);
         newtypeLabel.setVisible(false);
         resultLabel.setVisible(false);
         newresultLabel.setVisible(false);
         typeComboBox.setVisible(false);
         newtypeComboBox.setVisible(false);
         update.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_cancelUpdateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Disease.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Disease.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Disease.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Disease.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                try {
                    new Disease().setVisible(true);
                } catch (DiseasesDaoException ex) {
                    Logger.getLogger(Disease.class.getName()).log(Level.SEVERE, null, ex);
                } catch (DiseaseTypesDaoException ex) {
                    Logger.getLogger(Disease.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label1;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JTextField TextFieldSearch;
    private javax.swing.JButton addNewButton;
    private javax.swing.JButton cancelNewButton;
    private javax.swing.JButton cancelUpdateButton;
    private javax.swing.JButton confirmNewButton;
    private javax.swing.JButton confirmUpdateButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField newNameTextField;
    private javax.swing.JLabel newnameLabel;
    private javax.swing.JLabel newresultLabel;
    private javax.swing.JTextField newresultTextField;
    private javax.swing.JComboBox newtypeComboBox;
    private javax.swing.JLabel newtypeLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JTextField resultTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton showAll;
    private javax.swing.JTable showTable;
    private javax.swing.JComboBox typeComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel update;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
