
package settings.forms.general;

import com.Common;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import senior.hrms.emps.dto.Organ;
import senior.hrms.emps.dto.OrganPk;
import senior.hrms.emps.exceptions.OrganDaoException;
import settings.handler.general.OrganHandler;

/**
 *
 * @author amal
 */
public class Organs extends javax.swing.JFrame
{
    Common comObj;

    /**
     * Creates new form Organs
     */
    public Organs() throws OrganDaoException
    {
       
        initComponents();
        comObj = new Common();
        
//         Max frame width //
        int width =Integer.parseInt( comObj.resourceFile.getString("innerFrameSize") );
        comObj.setMaxFrameWidth(this, width);
        
        newNameLabel.setVisible(false);
        ButtonConfirm.setVisible(false);
        textfieldUpdate.setVisible(false);
        update.setVisible(false);
        cancelButton.setVisible(false);
        
        // put data into table
        OrganHandler oh = new OrganHandler();
        Organ[] list = oh.getAllOrgan();
        DefaultTableModel dtm = (DefaultTableModel) showTable.getModel();
        dtm.setRowCount(0);
        for(int i=0;i<list.length;i++)
        {
        Organ or = list[i];
        Vector row= new Vector();
        row.add(or.getOrganName());
        row.add(or.getOrganId());
        dtm.addRow(row);
        
        }
        showTable.setModel(dtm);
        showTable.updateUI();
         jScrollPane1.setViewportView(showTable);
        
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showTable = new javax.swing.JTable();
        TextFieldSearch = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();
        ButtonUpdate = new javax.swing.JButton();
        newNameLabel = new javax.swing.JLabel();
        textfieldUpdate = new javax.swing.JTextField();
        ButtonConfirm = new javax.swing.JButton();
        update = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        showAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(300, 300));
        setMinimumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(412, 300));
        setSize(new java.awt.Dimension(300, 300));

        jPanel1.setPreferredSize(new java.awt.Dimension(300, 300));

        Label1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label1.setForeground(new java.awt.Color(51, 51, 51));
        Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label1.setText("أعضاء الجسم");
        Label1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        showTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "الاسم ", "مسلسل"
            }
        ));
        jScrollPane1.setViewportView(showTable);

        TextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldSearchActionPerformed(evt);
            }
        });

        addButton.setText("اضافة جديد\n");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        SearchButton.setText("بحث");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        ButtonDelete.setText("حذف");
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        ButtonUpdate.setText("اختر للتحديث");
        ButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUpdateActionPerformed(evt);
            }
        });

        newNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        newNameLabel.setText("الاسم الجديد");

        ButtonConfirm.setText("تعديل");
        ButtonConfirm.setActionCommand("");
        ButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfirmActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update.setForeground(new java.awt.Color(204, 0, 0));
        update.setText("تم الحفظ بنجاح");

        cancelButton.setText("الغاء");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        showAll.setText("عرض الكل");
        showAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(showAll, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(74, 74, 74)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textfieldUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(newNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(219, 219, 219)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(TextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchButton)
                    .addComponent(addButton)
                    .addComponent(showAll))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDelete))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonConfirm)
                    .addComponent(cancelButton))
                .addGap(18, 18, 18)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldSearchActionPerformed
        // TODO add your handling codeupdateLabel
    }//GEN-LAST:event_TextFieldSearchActionPerformed

    private void ButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUpdateActionPerformed

      if(showTable.getSelectedRow()>=0)
   {
        newNameLabel.setVisible(true);
        ButtonConfirm.setVisible(true);
        cancelButton.setVisible(true);
        textfieldUpdate.setVisible(true);
        update.setVisible(false);
   }
        
    }
/* TODO add your handling code here:
    }         updateLabel//GEN-LAST:event_ButtonUpdateActionPerformed
*/
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        newNameLabel.setVisible(false);
        ButtonConfirm.setVisible(false);
        textfieldUpdate.setVisible(false);
         cancelButton.setVisible(false);
         if(TextFieldSearch.getText().length() == 0)
        {
         update.setVisible(false);
        }
        else 
        {
            try{
         String keyword = TextFieldSearch.getText();
         Organ dto =new Organ();
         dto.setOrganName(keyword);
         OrganHandler oh = new OrganHandler();
         oh.addOrgan(dto);
         update.setText("تم الاضافه بنجاح");
         update.setVisible(true);
            }
            catch(Exception ex){  }
       }
        
// TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        newNameLabel.setVisible(false);
        ButtonConfirm.setVisible(false);
        textfieldUpdate.setVisible(false);
        cancelButton.setVisible(false);
        update.setVisible(false);
        
        
            
         try{
        String keyword = TextFieldSearch.getText();
        OrganHandler oh = new OrganHandler();
        Organ[] list = oh.getOrganByName(keyword);
           
        DefaultTableModel dtm = (DefaultTableModel) showTable.getModel();
        dtm.setRowCount(0);
        for(int i=0;i<list.length;i++)
        {
        Organ or = list[i];
        Vector row= new Vector();
         row.add(or.getOrganName());
        row.add(or.getOrganId());
        dtm.addRow(row);
        
        }
        showTable.setModel(dtm);
        showTable.updateUI();
        jScrollPane1.setViewportView(showTable);
            }
            catch(Exception ex) {}
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void ButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfirmActionPerformed
        try{
        if(showTable.getSelectedRow()>=0)
   {
   int row = showTable.getSelectedRow();
   int culumn = 1;
   int valueOfId = Integer.parseInt(showTable.getValueAt(row, culumn).toString());
   String newNameOfOrgan = textfieldUpdate.getText();
        Organ or=new Organ();
        or.setOrganId(valueOfId);
        or.setOrganName(newNameOfOrgan);
        OrganPk pk=or.createPk();
        OrganHandler oh = new OrganHandler();
        oh.updateOrgan(pk, or);
        newNameLabel.setVisible(false);
        ButtonConfirm.setVisible(false);
        cancelButton.setVisible(false);
        textfieldUpdate.setVisible(false);
        update.setVisible(true);
        update.setText("تم التعديل بنجاح");
        }
        }
        catch(Exception ex){  }
        
        
    }//GEN-LAST:event_ButtonConfirmActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
  try{
        if(showTable.getSelectedRow()>=0)
   {
       newNameLabel.setVisible(false);
        ButtonConfirm.setVisible(false);
        textfieldUpdate.setVisible(false);
        cancelButton.setVisible(false);
   int row = showTable.getSelectedRow();
   int culumn = 1;
   int valueOfId = Integer.parseInt(showTable.getValueAt(row, culumn).toString());
    int confirm= JOptionPane.showConfirmDialog(rootPane, "هل انت متاكد بالحذف !");
         if(confirm==0)
         {
        Organ or=new Organ();
        or.setOrganId(valueOfId);
        OrganPk pk=or.createPk();
        OrganHandler oh = new OrganHandler();
        oh.deleteOrgan(pk);
         JOptionPane.showMessageDialog(rootPane,"تم الحذف بنجاح");
          newNameLabel.setVisible(false);
        ButtonConfirm.setVisible(false);
        textfieldUpdate.setVisible(false);
        cancelButton.setVisible(false);
         }
         }
   
  }
  catch(Exception ex){  }
    }
        
/* TODO add your handlupdateLabelde here:
    }              updateLabel//GEN-LAST:event_ButtonDeleteActionPerformed
*/
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        newNameLabel.setVisible(false);
        ButtonConfirm.setVisible(false);
        textfieldUpdate.setVisible(false);
        textfieldUpdate.setText("");
        cancelButton.setVisible(false);
        
        update.setVisible(false);// TODO add your handling code here:
        
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void showAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllActionPerformed
      newNameLabel.setVisible(false);
        ButtonConfirm.setVisible(false);
        textfieldUpdate.setVisible(false);
        update.setVisible(false);
        cancelButton.setVisible(false);
        
        // put data into table
        try{
        OrganHandler oh = new OrganHandler();
        Organ[] list = oh.getAllOrgan();
        DefaultTableModel dtm = (DefaultTableModel) showTable.getModel();
        dtm.setRowCount(0);
        for(int i=0;i<list.length;i++)
        {
        Organ or = list[i];
        Vector row= new Vector();
        row.add(or.getOrganName());
        row.add(or.getOrganId());
        dtm.addRow(row);
        
        }
        showTable.setModel(dtm);
        showTable.updateUI();
         jScrollPane1.setViewportView(showTable);
        }
        catch(Exception ex){  }
        
// TODO add your handling code here:
    }//GEN-LAST:event_showAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Organs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Organs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Organs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Organs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                try {
                    new Organs().setVisible(true);
                } catch (OrganDaoException ex) {
                    Logger.getLogger(Organs.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonConfirm;
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonUpdate;
    private javax.swing.JLabel Label1;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField TextFieldSearch;
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel newNameLabel;
    private javax.swing.JButton showAll;
    private javax.swing.JTable showTable;
    private javax.swing.JTextField textfieldUpdate;
    private javax.swing.JLabel update;
    // End of variables declaration//GEN-END:variables
}
